import { useEffect, useMemo, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';

import { baseApi } from '@shared/app/api/baseApi.js';
import { getApiErrorMessage } from '@shared/app/api/getApiErrorMessage.js';
import { RequestLoadingState } from '@shared/app/components/RequestLoader/RequestLoader.jsx';
import { useI18n } from '@shared/app/i18n/useI18n.js';
import { selectToken, selectUser, setSession } from '@shared/features/auth/authSlice.js';
import { saveSession } from '@shared/features/auth/authStorage.js';
import { useGetCompanyBillingQuery, useUpdateCompanyBillingMutation } from '../../features/worktrack/billingApi.js';
import { useGetCompanySettingsQuery, useGetWorkRulesQuery, useUpdateCompanySettingsMutation, useUpdateWorkRulesMutation } from '../../features/worktrack/worktrackApi.js';
import './CompanySettingsPage.css';

const BILLING_COPY={uk:{title:'Реквізити для фактур',copy:'Дані роботодавця, які потрапляють у фактури працівників.',ico:'IČO',dic:'DIČ / VAT ID',address:'Юридична адреса',email:'Email для фактур',save:'Зберегти реквізити',saving:'Збереження…',saved:'Реквізити збережено'},cs:{title:'Fakturační údaje',copy:'Údaje zaměstnavatele používané na fakturách pracovníků.',ico:'IČO',dic:'DIČ / VAT ID',address:'Fakturační adresa',email:'E-mail pro faktury',save:'Uložit fakturační údaje',saving:'Ukládání…',saved:'Fakturační údaje byly uloženy'},en:{title:'Company billing details',copy:'Employer details used on employee invoices.',ico:'Company ID (IČO)',dic:'VAT ID (DIČ)',address:'Billing address',email:'Invoice email',save:'Save billing details',saving:'Saving…',saved:'Billing details saved'}};
const WORK_COPY={uk:{title:'Робочий час',copy:'Обід і денна норма для понаднормових.',break:'Автоматична перерва на обід',none:'Не віднімати',min30:'30 хвилин',min60:'60 хвилин',norm:'Нормовані години на день',normHint:'Понаднормові рахуються з чистих годин після обіду.',save:'Зберегти правила',saving:'Збереження…',saved:'Правила збережено'},cs:{title:'Pracovní doba',copy:'Oběd a denní norma pro výpočet přesčasů.',break:'Automatická přestávka na oběd',none:'Neodečítat',min30:'30 minut',min60:'60 minut',norm:'Denní norma hodin',normHint:'Přesčas se počítá z čistých hodin po obědě.',save:'Uložit pravidla',saving:'Ukládání…',saved:'Pravidla byla uložena'},en:{title:'Working time',copy:'Lunch deduction and daily overtime standard.',break:'Automatic lunch break',none:'No deduction',min30:'30 minutes',min60:'60 minutes',norm:'Standard hours per day',normHint:'Overtime uses net hours after lunch.',save:'Save rules',saving:'Saving…',saved:'Rules saved'}};
const MENU_COPY={uk:{identity:'Компанія',identityCopy:'Назва та системні дані',workCopy:'Норма дня та обід',billingCopy:'IČO, DIČ, адреса та email',close:'Закрити'},cs:{identity:'Společnost',identityCopy:'Název a systémové údaje',workCopy:'Denní norma a oběd',billingCopy:'IČO, DIČ, adresa a e-mail',close:'Zavřít'},en:{identity:'Company',identityCopy:'Name and system details',workCopy:'Daily standard and lunch',billingCopy:'IČO, VAT ID, address and email',close:'Close'}};
const emptyBilling={ico:'',dic:'',address:'',email:''};

export function CompanySettingsPage(){
 const dispatch=useDispatch(); const user=useSelector(selectUser); const token=useSelector(selectToken); const {language,t}=useI18n();
 const bc=BILLING_COPY[language]||BILLING_COPY.uk; const wc=WORK_COPY[language]||WORK_COPY.uk; const mc=MENU_COPY[language]||MENU_COPY.uk;
 const {data,error,isLoading}=useGetCompanySettingsQuery(); const [updateCompanySettings,updateState]=useUpdateCompanySettingsMutation();
 const {data:workRulesData,error:workRulesError,isLoading:workRulesLoading}=useGetWorkRulesQuery(); const [updateWorkRules,workRulesUpdateState]=useUpdateWorkRulesMutation();
 const {data:billingData,error:billingError,isLoading:billingLoading}=useGetCompanyBillingQuery(); const [updateCompanyBilling,billingUpdateState]=useUpdateCompanyBillingMutation();
 const [modal,setModal]=useState(''); const [billing,setBilling]=useState(emptyBilling); const [billingMessage,setBillingMessage]=useState(''); const [billingActionError,setBillingActionError]=useState('');
 const [breakMinutes,setBreakMinutes]=useState('0'); const [standardDailyHours,setStandardDailyHours]=useState('8.00'); const [workRulesMessage,setWorkRulesMessage]=useState(''); const [workRulesActionError,setWorkRulesActionError]=useState('');
 const [name,setName]=useState(''); const [message,setMessage]=useState(''); const [actionError,setActionError]=useState('');
 const company=data?.company||null; const normalizedName=name.trim(); const hasChanges=useMemo(()=>Boolean(company&&normalizedName&&normalizedName!==String(company.name||'').trim()),[company,normalizedName]);
 useEffect(()=>{if(company?.name)setName(company.name)},[company?.name]);
 useEffect(()=>{if(billingData?.company?.billingProfile)setBilling({...emptyBilling,...billingData.company.billingProfile})},[billingData]);
 useEffect(()=>{if(workRulesData?.workRules){setBreakMinutes(String(workRulesData.workRules.breakMinutes??0));setStandardDailyHours(String(workRulesData.workRules.standardDailyHours??'8.00'))}},[workRulesData]);
 useEffect(()=>{const section=new URLSearchParams(window.location.search).get('section');if(['identity','work','billing'].includes(section))setModal(section)},[]);
 function close(){setModal('');setActionError('');setBillingActionError('');setWorkRulesActionError('')}
 function syncCompanyIntoSession(updatedCompany){if(!user||!token||!updatedCompany?.id)return;const nextUser={...user,activeCompany:{...(user.activeCompany||{}),...updatedCompany},activeMembership:user.activeMembership?{...user.activeMembership,company:{...(user.activeMembership.company||{}),...updatedCompany}}:user.activeMembership,memberships:Array.isArray(user.memberships)?user.memberships.map(m=>m.companyId===updatedCompany.id||m.company?.id===updatedCompany.id?{...m,company:{...(m.company||{}),...updatedCompany}}:m):user.memberships};saveSession(token,nextUser);dispatch(setSession({token,user:nextUser}));dispatch(baseApi.util.invalidateTags([{type:'Me',id:'CURRENT'},{type:'WorkEntries',id:'SUMMARY'},{type:'WorkEntries',id:'PAYROLL'}]))}
 async function submitCompany(e){e.preventDefault();setMessage('');setActionError('');if(!normalizedName){setActionError(t('company.nameRequired'));return}try{const result=await updateCompanySettings({name:normalizedName}).unwrap();const updatedCompany=result?.company||null;if(updatedCompany)syncCompanyIntoSession(updatedCompany);setName(updatedCompany?.name||normalizedName);setMessage(t('company.savedMessage'))}catch(err){setActionError(getApiErrorMessage(err))}}
 async function submitWorkRules(e){e.preventDefault();setWorkRulesMessage('');setWorkRulesActionError('');try{const result=await updateWorkRules({breakMinutes:Number(breakMinutes),standardDailyHours}).unwrap();setBreakMinutes(String(result.workRules.breakMinutes));setStandardDailyHours(String(result.workRules.standardDailyHours));setWorkRulesMessage(wc.saved)}catch(err){setWorkRulesActionError(getApiErrorMessage(err))}}
 async function submitBilling(e){e.preventDefault();setBillingMessage('');setBillingActionError('');try{const result=await updateCompanyBilling(billing).unwrap();setBilling({...emptyBilling,...result.company?.billingProfile});setBillingMessage(bc.saved)}catch(err){setBillingActionError(getApiErrorMessage(err))}}
 const setBillingField=(key,value)=>{setBillingMessage('');setBilling(current=>({...current,[key]:value}))};
 const workSummary=workRulesError?wc.copy:`${standardDailyHours || '8.00'} h · ${Number(breakMinutes) ? `${breakMinutes} min` : wc.none}`;
 const billingSummary=billingError?bc.copy:([billing.ico,billing.dic].filter(Boolean).join(' · ')||bc.copy);
 return <section className="companySettingsPage pageStack">
  <header className="companySettingsHeader appTop"><div className="appTitleBlock"><p className="sectionEyebrow">{t('company.eyebrow')}</p><h1>{t('company.title')}</h1><p>{company?.name||t('company.current')}</p></div></header>
  {(isLoading||workRulesLoading||billingLoading)?<RequestLoadingState label={t('company.loading')} />:null}
  {error?<p className="statusNote is-error">{getApiErrorMessage(error)}</p>:null}
  {workRulesError?<p className="statusNote is-error">{getApiErrorMessage(workRulesError)}</p>:null}
  {billingError?<p className="statusNote is-error">{getApiErrorMessage(billingError)}</p>:null}
  <section className="companySettingsMenu screenCard">
   <button type="button" disabled={Boolean(error)||isLoading} onClick={()=>setModal('identity')}><span className="companySettingsMenuIcon">🏢</span><span><strong>{mc.identity}</strong><small>{company?.name||mc.identityCopy}</small></span><b>›</b></button>
   <button type="button" disabled={Boolean(workRulesError)||workRulesLoading} onClick={()=>setModal('work')}><span className="companySettingsMenuIcon">🕘</span><span><strong>{wc.title}</strong><small>{workSummary}</small></span><b>›</b></button>
   <button type="button" disabled={Boolean(billingError)||billingLoading} onClick={()=>setModal('billing')}><span className="companySettingsMenuIcon">🧾</span><span><strong>{bc.title}</strong><small>{billingSummary}</small></span><b>›</b></button>
  </section>

  {modal?<div className="companySettingsModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="companySettingsModal" role="dialog" aria-modal="true"><header><h2>{modal==='identity'?mc.identity:modal==='work'?wc.title:bc.title}</h2><button type="button" aria-label={mc.close} onClick={close}>×</button></header>
   {modal==='identity'?<form className="companySettingsModalBody" onSubmit={submitCompany}>{isLoading?<RequestLoadingState label={t('company.loading')} />:null}<label className="companySettingsField"><span>{t('company.name')}</span><input type="text" autoComplete="organization" maxLength={120} value={name} onChange={e=>{setName(e.target.value);setMessage('')}} required /></label>{company?<div className="companySettingsMetaCard"><div className="companySettingsMeta"><span>{t('company.slug')}</span><strong>{company.slug||'-'}</strong></div></div>:null}{message?<p className="statusNote is-success">{message}</p>:null}{actionError?<p className="statusNote is-error">{actionError}</p>:null}<button className="companySettingsButton" disabled={updateState.isLoading||!hasChanges}>{updateState.isLoading?t('company.saving'):hasChanges?t('company.saveChanges'):t('company.saved')}</button></form>:null}
   {modal==='work'?<form className="companySettingsModalBody" onSubmit={submitWorkRules}>{workRulesError?<p className="statusNote is-error">{getApiErrorMessage(workRulesError)}</p>:null}<label className="companySettingsField"><span>{wc.break}</span><select value={breakMinutes} onChange={e=>{setBreakMinutes(e.target.value);setWorkRulesMessage('')}}><option value="0">{wc.none}</option><option value="30">{wc.min30}</option><option value="60">{wc.min60}</option></select></label><label className="companySettingsField"><span>{wc.norm}</span><input type="number" min="0.25" max="24" step="0.25" value={standardDailyHours} onChange={e=>{setStandardDailyHours(e.target.value);setWorkRulesMessage('')}} /></label><p className="companySettingsHelp">{wc.normHint}</p>{workRulesMessage?<p className="statusNote is-success">{workRulesMessage}</p>:null}{workRulesActionError?<p className="statusNote is-error">{workRulesActionError}</p>:null}<button className="companySettingsButton" disabled={workRulesUpdateState.isLoading}>{workRulesUpdateState.isLoading?wc.saving:wc.save}</button></form>:null}
   {modal==='billing'?<form className="companySettingsModalBody" onSubmit={submitBilling}>{billingError?<p className="statusNote is-error">{getApiErrorMessage(billingError)}</p>:null}<div className="companyBillingGrid"><label className="companySettingsField"><span>{bc.ico}</span><input value={billing.ico} onChange={e=>setBillingField('ico',e.target.value)} /></label><label className="companySettingsField"><span>{bc.dic}</span><input value={billing.dic} onChange={e=>setBillingField('dic',e.target.value)} /></label><label className="companySettingsField companyBillingWide"><span>{bc.address}</span><input value={billing.address} onChange={e=>setBillingField('address',e.target.value)} /></label><label className="companySettingsField companyBillingWide"><span>{bc.email}</span><input type="email" value={billing.email} onChange={e=>setBillingField('email',e.target.value)} /></label></div>{billingMessage?<p className="statusNote is-success">{billingMessage}</p>:null}{billingActionError?<p className="statusNote is-error">{billingActionError}</p>:null}<button className="companySettingsButton" disabled={billingUpdateState.isLoading}>{billingUpdateState.isLoading?bc.saving:bc.save}</button></form>:null}
  </section></div>:null}
 </section>;
}
