import { useMemo, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useNavigate, useSearchParams } from 'react-router-dom';

import { baseApi } from '@shared/app/api/baseApi.js';
import { getApiErrorMessage } from '@shared/app/api/getApiErrorMessage.js';
import { BackButton } from '@shared/app/components/BackButton/BackButton.jsx';
import { RequestLoadingState } from '@shared/app/components/RequestLoader/RequestLoader.jsx';
import { useI18n } from '@shared/app/i18n/useI18n.js';
import { selectToken, selectUser, setSession } from '@shared/features/auth/authSlice.js';
import { saveSession } from '@shared/features/auth/authStorage.js';
import { useGetCompanyBillingQuery, useUpdateCompanyBillingMutation } from '../../features/worktrack/billingApi.js';
import { useGetCompanySettingsQuery, useGetWorkRulesQuery, useUpdateCompanySettingsMutation, useUpdateWorkRulesMutation } from '../../features/worktrack/worktrackApi.js';
import './CompanySettingsPage.css';

const BILLING_COPY={uk:{title:'Реквізити для фактур',copy:'Дані роботодавця, які потрапляють у фактури працівників.',ico:'IČO',dic:'DIČ / VAT ID',address:'Юридична адреса',email:'Email для фактур',save:'Зберегти реквізити',saving:'Збереження…',saved:'Реквізити збережено'},cs:{title:'Fakturační údaje',copy:'Údaje zaměstnavatele používané na fakturách pracovníků.',ico:'IČO',dic:'DIČ / VAT ID',address:'Fakturační adresa',email:'E-mail pro faktury',save:'Uložit fakturační údaje',saving:'Ukládání…',saved:'Fakturační údaje byly uloženy'},en:{title:'Company billing details',copy:'Employer details used on employee invoices.',ico:'Company ID (IČO)',dic:'VAT ID (DIČ)',address:'Billing address',email:'Invoice email',save:'Save billing details',saving:'Saving…',saved:'Billing details saved'}};
const WORK_COPY={uk:{title:'Робочий час',copy:'Обід і денна норма для понаднормових.',break:'Автоматична перерва на обід',none:'Не віднімати',min30:'30 хвилин',min60:'60 хвилин',norm:'Нормовані години на день',normHint:'Понаднормові рахуються з чистих годин після обіду.',save:'Зберегти правила',saving:'Збереження…',saved:'Правила збережено'},cs:{title:'Pracovní doba',copy:'Oběd a denní norma pro výpočet přesčasů.',break:'Automatická přestávka na oběd',none:'Neodečítat',min30:'30 minut',min60:'60 minut',norm:'Denní norma hodin',normHint:'Přesčas se počítá z čistých hodin po obědě.',save:'Uložit pravidla',saving:'Ukládání…',saved:'Pravidla byla uložena'},en:{title:'Working time',copy:'Lunch deduction and daily overtime standard.',break:'Automatic lunch break',none:'No deduction',min30:'30 minutes',min60:'60 minutes',norm:'Standard hours per day',normHint:'Overtime uses net hours after lunch.',save:'Save rules',saving:'Saving…',saved:'Rules saved'}};
const MENU_COPY={uk:{identity:'Компанія',identityCopy:'Назва та системні дані'},cs:{identity:'Společnost',identityCopy:'Název a systémové údaje'},en:{identity:'Company',identityCopy:'Name and system details'}};
const emptyBilling={ico:'',dic:'',address:'',email:''};
const DETAIL_SECTIONS=['identity','work','billing'];

export function CompanySettingsPage(){
 const dispatch=useDispatch(); const navigate=useNavigate(); const [searchParams]=useSearchParams(); const user=useSelector(selectUser); const token=useSelector(selectToken); const {language,t}=useI18n();
 const bc=BILLING_COPY[language]||BILLING_COPY.uk; const wc=WORK_COPY[language]||WORK_COPY.uk; const mc=MENU_COPY[language]||MENU_COPY.uk;
 const requestedSection=searchParams.get('section')||''; const section=DETAIL_SECTIONS.includes(requestedSection)?requestedSection:''; const fromSettings=searchParams.get('from')==='settings'; const backTo=fromSettings?'/more':'/company-settings';
 const {data,error,isLoading}=useGetCompanySettingsQuery(); const [updateCompanySettings,updateState]=useUpdateCompanySettingsMutation();
 const {data:workRulesData,error:workRulesError,isLoading:workRulesLoading}=useGetWorkRulesQuery(); const [updateWorkRules,workRulesUpdateState]=useUpdateWorkRulesMutation();
 const {data:billingData,error:billingError,isLoading:billingLoading}=useGetCompanyBillingQuery(); const [updateCompanyBilling,billingUpdateState]=useUpdateCompanyBillingMutation();
 const company=data?.company||null;
 const [name,setName]=useState(company?.name||''); const [message,setMessage]=useState(''); const [actionError,setActionError]=useState('');
 const [billing,setBilling]=useState(billingData?.company?.billingProfile?{...emptyBilling,...billingData.company.billingProfile}:emptyBilling); const [billingMessage,setBillingMessage]=useState(''); const [billingActionError,setBillingActionError]=useState('');
 const [breakMinutes,setBreakMinutes]=useState(String(workRulesData?.workRules?.breakMinutes??0)); const [standardDailyHours,setStandardDailyHours]=useState(String(workRulesData?.workRules?.standardDailyHours??'8.00')); const [workRulesMessage,setWorkRulesMessage]=useState(''); const [workRulesActionError,setWorkRulesActionError]=useState('');
 const effectiveName=name||company?.name||''; const normalizedName=effectiveName.trim(); const hasChanges=useMemo(()=>Boolean(company&&normalizedName&&normalizedName!==String(company.name||'').trim()),[company,normalizedName]);
 const currentBilling=billingData?.company?.billingProfile&&!billing.ico&&!billing.dic&&!billing.address&&!billing.email?{...emptyBilling,...billingData.company.billingProfile}:billing;
 const currentBreak=workRulesData?.workRules&&breakMinutes==='0'?String(workRulesData.workRules.breakMinutes??0):breakMinutes;
 const currentNorm=workRulesData?.workRules&&standardDailyHours==='8.00'?String(workRulesData.workRules.standardDailyHours??'8.00'):standardDailyHours;

 function syncCompanyIntoSession(updatedCompany){if(!user||!token||!updatedCompany?.id)return;const nextUser={...user,activeCompany:{...(user.activeCompany||{}),...updatedCompany},activeMembership:user.activeMembership?{...user.activeMembership,company:{...(user.activeMembership.company||{}),...updatedCompany}}:user.activeMembership,memberships:Array.isArray(user.memberships)?user.memberships.map(m=>m.companyId===updatedCompany.id||m.company?.id===updatedCompany.id?{...m,company:{...(m.company||{}),...updatedCompany}}:m):user.memberships};saveSession(token,nextUser);dispatch(setSession({token,user:nextUser}));dispatch(baseApi.util.invalidateTags([{type:'Me',id:'CURRENT'},{type:'WorkEntries',id:'SUMMARY'},{type:'WorkEntries',id:'PAYROLL'}]))}
 async function submitCompany(e){e.preventDefault();setMessage('');setActionError('');if(!normalizedName){setActionError(t('company.nameRequired'));return}try{const result=await updateCompanySettings({name:normalizedName}).unwrap();const updatedCompany=result?.company||null;if(updatedCompany)syncCompanyIntoSession(updatedCompany);setName(updatedCompany?.name||normalizedName);setMessage(t('company.savedMessage'))}catch(err){setActionError(getApiErrorMessage(err))}}
 async function submitWorkRules(e){e.preventDefault();setWorkRulesMessage('');setWorkRulesActionError('');try{const result=await updateWorkRules({breakMinutes:Number(currentBreak),standardDailyHours:currentNorm}).unwrap();setBreakMinutes(String(result.workRules.breakMinutes));setStandardDailyHours(String(result.workRules.standardDailyHours));setWorkRulesMessage(wc.saved)}catch(err){setWorkRulesActionError(getApiErrorMessage(err))}}
 async function submitBilling(e){e.preventDefault();setBillingMessage('');setBillingActionError('');try{const result=await updateCompanyBilling(currentBilling).unwrap();setBilling({...emptyBilling,...result.company?.billingProfile});setBillingMessage(bc.saved)}catch(err){setBillingActionError(getApiErrorMessage(err))}}
 const setBillingField=(key,value)=>{setBillingMessage('');setBilling(current=>({...currentBilling,...current,[key]:value}))};
 const workSummary=workRulesError?wc.copy:`${currentNorm || '8.00'} h · ${Number(currentBreak) ? `${currentBreak} min` : wc.none}`;
 const billingSummary=billingError?bc.copy:([currentBilling.ico,currentBilling.dic].filter(Boolean).join(' · ')||bc.copy);
 const detailTitle=section==='identity'?mc.identity:section==='work'?wc.title:bc.title;

 if(section){return <section className="companySettingsPage companySettingsDetailPage pageStack">
  <header className="companySettingsDetailHeader appTop"><BackButton to={backTo}/><div className="appTitleBlock"><h1>{detailTitle}</h1><p>{section==='identity'?(company?.name||mc.identityCopy):section==='work'?wc.copy:bc.copy}</p></div></header>
  {(section==='identity'&&isLoading)||(section==='work'&&workRulesLoading)||(section==='billing'&&billingLoading)?<RequestLoadingState label={t('company.loading')} />:null}
  <section className="companySettingsDetailCard screenCard">
   {section==='identity'?<form className="companySettingsDetailBody" onSubmit={submitCompany}><label className="companySettingsField"><span>{t('company.name')}</span><input type="text" autoComplete="organization" maxLength={120} value={effectiveName} onChange={e=>{setName(e.target.value);setMessage('')}} required /></label>{company?<div className="companySettingsMetaCard"><div className="companySettingsMeta"><span>{t('company.slug')}</span><strong>{company.slug||'-'}</strong></div></div>:null}{message?<p className="statusNote is-success">{message}</p>:null}{actionError?<p className="statusNote is-error">{actionError}</p>:null}{error?<p className="statusNote is-error">{getApiErrorMessage(error)}</p>:null}<button className="companySettingsButton" disabled={updateState.isLoading||!hasChanges}>{updateState.isLoading?t('company.saving'):hasChanges?t('company.saveChanges'):t('company.saved')}</button></form>:null}
   {section==='work'?<form className="companySettingsDetailBody" onSubmit={submitWorkRules}>{workRulesError?<p className="statusNote is-error">{getApiErrorMessage(workRulesError)}</p>:null}<label className="companySettingsField"><span>{wc.break}</span><select value={currentBreak} onChange={e=>{setBreakMinutes(e.target.value);setWorkRulesMessage('')}}><option value="0">{wc.none}</option><option value="30">{wc.min30}</option><option value="60">{wc.min60}</option></select></label><label className="companySettingsField"><span>{wc.norm}</span><input type="number" min="0.25" max="24" step="0.25" value={currentNorm} onChange={e=>{setStandardDailyHours(e.target.value);setWorkRulesMessage('')}} /></label><p className="companySettingsHelp">{wc.normHint}</p>{workRulesMessage?<p className="statusNote is-success">{workRulesMessage}</p>:null}{workRulesActionError?<p className="statusNote is-error">{workRulesActionError}</p>:null}<button className="companySettingsButton" disabled={workRulesUpdateState.isLoading}>{workRulesUpdateState.isLoading?wc.saving:wc.save}</button></form>:null}
   {section==='billing'?<form className="companySettingsDetailBody" onSubmit={submitBilling}>{billingError?<p className="statusNote is-error">{getApiErrorMessage(billingError)}</p>:null}<div className="companyBillingGrid"><label className="companySettingsField"><span>{bc.ico}</span><input value={currentBilling.ico} onChange={e=>setBillingField('ico',e.target.value)} /></label><label className="companySettingsField"><span>{bc.dic}</span><input value={currentBilling.dic} onChange={e=>setBillingField('dic',e.target.value)} /></label><label className="companySettingsField companyBillingWide"><span>{bc.address}</span><input value={currentBilling.address} onChange={e=>setBillingField('address',e.target.value)} /></label><label className="companySettingsField companyBillingWide"><span>{bc.email}</span><input type="email" value={currentBilling.email} onChange={e=>setBillingField('email',e.target.value)} /></label></div>{billingMessage?<p className="statusNote is-success">{billingMessage}</p>:null}{billingActionError?<p className="statusNote is-error">{billingActionError}</p>:null}<button className="companySettingsButton" disabled={billingUpdateState.isLoading}>{billingUpdateState.isLoading?bc.saving:bc.save}</button></form>:null}
  </section>
 </section>}

 return <section className="companySettingsPage pageStack">
  <header className="companySettingsHeader appTop"><div className="appTitleBlock"><p className="sectionEyebrow">{t('company.eyebrow')}</p><h1>{t('company.title')}</h1><p>{company?.name||t('company.current')}</p></div></header>
  {(isLoading||workRulesLoading||billingLoading)?<RequestLoadingState label={t('company.loading')} />:null}
  <section className="companySettingsMenu screenCard">
   <button type="button" disabled={Boolean(error)||isLoading} onClick={()=>navigate('/company-settings?section=identity')}><span className="companySettingsMenuIcon">🏢</span><span><strong>{mc.identity}</strong><small>{company?.name||mc.identityCopy}</small></span><b>›</b></button>
   <button type="button" disabled={Boolean(workRulesError)||workRulesLoading} onClick={()=>navigate('/company-settings?section=work')}><span className="companySettingsMenuIcon">🕘</span><span><strong>{wc.title}</strong><small>{workSummary}</small></span><b>›</b></button>
   <button type="button" disabled={Boolean(billingError)||billingLoading} onClick={()=>navigate('/company-settings?section=billing')}><span className="companySettingsMenuIcon">🧾</span><span><strong>{bc.title}</strong><small>{billingSummary}</small></span><b>›</b></button>
  </section>
 </section>;
}
