import { useState } from 'react';

import { getApiErrorMessage } from '@shared/app/api/getApiErrorMessage.js';
import { RequestLoadingState } from '@shared/app/components/RequestLoader/RequestLoader.jsx';
import { SvgIcon } from '@shared/app/components/SvgIcon/SvgIcon.jsx';
import { useI18n } from '@shared/app/i18n/useI18n.js';
import {
  useCreateManagerEmployeeMutation,
  useGetManagerEmployeesQuery,
  useResetManagerEmployeePasswordMutation,
  useUpdateManagerEmployeeMutation,
} from '../../features/worktrack/worktrackApi.js';
import './EmployeesPage.css';

const EMPTY_EMPLOYEE_FORM = { firstName: '', lastName: '', email: '', temporaryPassword: '', hourlyRateCzk: '' };
const EMPTY_EMPLOYEES = [];
const TEXT = {
  uk: { employee:'Працівник',team:'Команда',title:'Працівники',active:'активних',total:'всього',addEmployee:'Додати працівника',addCopy:'Працівник повинен змінити тимчасовий пароль після першого входу.',firstName:'Ім’я',lastName:'Прізвище',email:'E-mail',temporaryPassword:'Тимчасовий пароль',hourlyRate:'Погодинна ставка CZK',employeeAdded:'Працівника додано.',rateUpdated:'Погодинну ставку оновлено.',reactivated:'Працівника знову активовано.',deactivated:'Працівника деактивовано.',passwordMin:'Тимчасовий пароль має містити щонайменше 8 символів.',passwordReset:'Пароль скинуто для {name}.',list:'Список працівників',currentWeek:'Поточний тиждень',loading:'Завантаження працівників',none:'Працівників ще немає',week:'тиждень',pending:'очікує',status:'статус',rate:'Ставка CZK',saveRate:'Зберегти ставку',deactivate:'Деактивувати',reactivate:'Активувати',resetPassword:'Скинути пароль',newTemporaryPassword:'Новий тимчасовий пароль',minPlaceholder:'Щонайменше 8 символів',resetCopy:'Активні сесії буде завершено. Працівник повинен змінити цей пароль після входу.',setTemporaryPassword:'Встановити тимчасовий пароль',activeStatus:'Активний',inactiveStatus:'Неактивний',manage:'Керувати',close:'Закрити',employeeDetails:'Дані працівника',actions:'Дії',cancel:'Скасувати' },
  en: { employee:'Employee',team:'Team',title:'Employees',active:'active',total:'total',addEmployee:'Add employee',addCopy:'The employee must replace the temporary password after the first sign in.',firstName:'First name',lastName:'Last name',email:'Email',temporaryPassword:'Temporary password',hourlyRate:'Hourly rate CZK',employeeAdded:'Employee added.',rateUpdated:'Hourly rate updated.',reactivated:'Employee reactivated.',deactivated:'Employee deactivated.',passwordMin:'Temporary password must be at least 8 characters long.',passwordReset:'Password reset for {name}.',list:'Employee list',currentWeek:'Current week',loading:'Loading employees',none:'No employees yet',week:'week',pending:'pending',status:'status',rate:'Rate CZK',saveRate:'Save rate',deactivate:'Deactivate',reactivate:'Reactivate',resetPassword:'Reset password',newTemporaryPassword:'New temporary password',minPlaceholder:'At least 8 characters',resetCopy:'Existing sessions will be signed out. The employee must change this password after signing in.',setTemporaryPassword:'Set temporary password',activeStatus:'Active',inactiveStatus:'Inactive',manage:'Manage',close:'Close',employeeDetails:'Employee details',actions:'Actions',cancel:'Cancel' },
  cs: { employee:'Zaměstnanec',team:'Tým',title:'Zaměstnanci',active:'aktivních',total:'celkem',addEmployee:'Přidat zaměstnance',addCopy:'Zaměstnanec musí po prvním přihlášení změnit dočasné heslo.',firstName:'Jméno',lastName:'Příjmení',email:'E-mail',temporaryPassword:'Dočasné heslo',hourlyRate:'Hodinová sazba CZK',employeeAdded:'Zaměstnanec byl přidán.',rateUpdated:'Hodinová sazba byla aktualizována.',reactivated:'Zaměstnanec byl znovu aktivován.',deactivated:'Zaměstnanec byl deaktivován.',passwordMin:'Dočasné heslo musí mít alespoň 8 znaků.',passwordReset:'Heslo pro {name} bylo resetováno.',list:'Seznam zaměstnanců',currentWeek:'Aktuální týden',loading:'Načítání zaměstnanců',none:'Zatím žádní zaměstnanci',week:'týden',pending:'čeká',status:'stav',rate:'Sazba CZK',saveRate:'Uložit sazbu',deactivate:'Deaktivovat',reactivate:'Aktivovat',resetPassword:'Resetovat heslo',newTemporaryPassword:'Nové dočasné heslo',minPlaceholder:'Alespoň 8 znaků',resetCopy:'Aktivní relace budou ukončeny. Zaměstnanec musí toto heslo po přihlášení změnit.',setTemporaryPassword:'Nastavit dočasné heslo',activeStatus:'Aktivní',inactiveStatus:'Neaktivní',manage:'Spravovat',close:'Zavřít',employeeDetails:'Údaje zaměstnance',actions:'Akce',cancel:'Zrušit' },
};

function getEmployeeName(employee, fallback) { return employee?.name || employee?.email || fallback; }

export function EmployeesPage() {
  const { language } = useI18n(); const copy = TEXT[language] || TEXT.uk;
  const { data, error, isLoading } = useGetManagerEmployeesQuery();
  const [createManagerEmployee, createState] = useCreateManagerEmployeeMutation(); const [updateManagerEmployee, updateState] = useUpdateManagerEmployeeMutation(); const [resetManagerEmployeePassword, resetState] = useResetManagerEmployeePasswordMutation();
  const [form, setForm] = useState(EMPTY_EMPLOYEE_FORM); const [modal, setModal] = useState(''); const [selectedEmployeeId, setSelectedEmployeeId] = useState(''); const [rateDraft, setRateDraft] = useState(''); const [resetPassword, setResetPassword] = useState(''); const [actionError, setActionError] = useState(''); const [actionSuccess, setActionSuccess] = useState('');
  const employees = Array.isArray(data?.employees) ? data.employees : EMPTY_EMPLOYEES; const activeEmployeeCount = employees.filter(employee => employee.status === 'ACTIVE').length; const selectedEmployee = employees.find(employee => employee.id === selectedEmployeeId) || null; const isMutating = createState.isLoading || updateState.isLoading || resetState.isLoading; const hasEmployeeList = !isLoading && !error;
  function clearMessages(){setActionError('');setActionSuccess('')} function updateForm(field,value){setForm(current=>({...current,[field]:value}))}
  function openManage(employee){clearMessages();setSelectedEmployeeId(employee.id);setRateDraft(employee.hourlyRateCzk || '0.00');setResetPassword('');setModal('manage')}
  function closeModal(){setModal('');setResetPassword('');setActionError('')}
  async function submitEmployee(event){event.preventDefault();clearMessages();try{await createManagerEmployee(form).unwrap();setForm(EMPTY_EMPLOYEE_FORM);setActionSuccess(copy.employeeAdded);setModal('')}catch(e){setActionError(getApiErrorMessage(e))}}
  async function saveRate(){if(!selectedEmployee)return;clearMessages();try{await updateManagerEmployee({employeeId:selectedEmployee.id,hourlyRateCzk:rateDraft}).unwrap();setActionSuccess(copy.rateUpdated)}catch(e){setActionError(getApiErrorMessage(e))}}
  async function toggleEmployeeStatus(){if(!selectedEmployee)return;clearMessages();const nextStatus=selectedEmployee.status==='ACTIVE'?'INACTIVE':'ACTIVE';try{await updateManagerEmployee({employeeId:selectedEmployee.id,status:nextStatus}).unwrap();setActionSuccess(nextStatus==='ACTIVE'?copy.reactivated:copy.deactivated)}catch(e){setActionError(getApiErrorMessage(e))}}
  async function submitPasswordReset(event){event.preventDefault();if(!selectedEmployee)return;clearMessages();if(resetPassword.length<8){setActionError(copy.passwordMin);return}try{await resetManagerEmployeePassword({employeeId:selectedEmployee.id,temporaryPassword:resetPassword}).unwrap();setResetPassword('');setActionSuccess(copy.passwordReset.replace('{name}',getEmployeeName(selectedEmployee,copy.employee)));setModal('manage')}catch(e){setActionError(getApiErrorMessage(e))}}

  return <section className="employeesPage pageStack">
    <header className="employeesHeader appTop"><div className="appTitleBlock"><p className="sectionEyebrow">{copy.team}</p><h1>{copy.title}</h1>{hasEmployeeList?<p>{activeEmployeeCount} {copy.active} · {employees.length} {copy.total}</p>:null}</div><button className="employeesAddTop" type="button" onClick={()=>{setForm(EMPTY_EMPLOYEE_FORM);clearMessages();setModal('add')}}>+ {copy.addEmployee}</button></header>
    {actionSuccess?<p className="statusNote is-success">{actionSuccess}</p>:null}
    <section className="employeesPanel screenCard"><div className="compactHeader"><h2>{copy.list}</h2>{hasEmployeeList?<p>{data?.week?`${data.week.weekStart} - ${data.week.weekEnd}`:copy.currentWeek}</p>:null}</div>{isLoading?<RequestLoadingState label={copy.loading}/>:null}{error?<p className="statusNote is-error">{getApiErrorMessage(error)}</p>:null}{hasEmployeeList&&!employees.length?<div className="employeesEmpty"><span aria-hidden="true"><SvgIcon name="accounts"/></span><strong>{copy.none}</strong></div>:null}
      {hasEmployeeList&&employees.length?<div className="employeesList">{employees.map(employee=>{const isActive=employee.status==='ACTIVE';return <button className={`employeeCard${isActive?'':' is-inactive'}`} type="button" key={employee.id} onClick={()=>openManage(employee)}><div className="employeeCard-main"><span className="employeeCard-avatar">{getEmployeeName(employee,copy.employee).slice(0,1).toUpperCase()}</span><div><strong>{getEmployeeName(employee,copy.employee)}</strong><p>{employee.email}</p></div></div><div className="employeeCard-metrics"><span><strong>{employee.summary?.totalHours||'0.00'} h</strong><em>{copy.week}</em></span><span><strong>{employee.pendingSubmissions||0}</strong><em>{copy.pending}</em></span><span><strong>{isActive?copy.activeStatus:copy.inactiveStatus}</strong><em>{copy.status}</em></span></div><span className="employeeCard-chevron">›</span></button>})}</div>:null}
    </section>

    {modal?<div className="employeesModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closeModal()}}><section className={`employeesModal${modal==='manage'?' is-drawer':''}`} role="dialog" aria-modal="true"><header><div><span>{copy.team}</span><h2>{modal==='add'?copy.addEmployee:modal==='password'?copy.resetPassword:getEmployeeName(selectedEmployee,copy.employee)}</h2></div><button type="button" aria-label={copy.close} onClick={closeModal}>×</button></header>
      {modal==='add'?<form className="employeesModalBody" onSubmit={submitEmployee}><p className="employeesModalCopy">{copy.addCopy}</p><div className="employeesFormGrid"><label className="employeesField"><span>{copy.firstName}</span><input type="text" value={form.firstName} onChange={e=>updateForm('firstName',e.target.value)} required/></label><label className="employeesField"><span>{copy.lastName}</span><input type="text" value={form.lastName} onChange={e=>updateForm('lastName',e.target.value)}/></label></div><label className="employeesField"><span>{copy.email}</span><input type="email" value={form.email} onChange={e=>updateForm('email',e.target.value)} required/></label><div className="employeesFormGrid"><label className="employeesField"><span>{copy.temporaryPassword}</span><input type="password" minLength={8} value={form.temporaryPassword} onChange={e=>updateForm('temporaryPassword',e.target.value)} required/></label><label className="employeesField"><span>{copy.hourlyRate}</span><input inputMode="decimal" type="number" min="0" step="0.01" value={form.hourlyRateCzk} onChange={e=>updateForm('hourlyRateCzk',e.target.value)}/></label></div>{actionError?<p className="statusNote is-error">{actionError}</p>:null}<button className="employeesPrimaryButton" disabled={isMutating}>{copy.addEmployee}</button></form>:null}
      {modal==='manage'&&selectedEmployee?<div className="employeesModalBody"><section className="employeeDetailHero"><span className="employeeDetailAvatar">{getEmployeeName(selectedEmployee,copy.employee).slice(0,1).toUpperCase()}</span><div><strong>{getEmployeeName(selectedEmployee,copy.employee)}</strong><p>{selectedEmployee.email}</p></div><em className={selectedEmployee.status==='ACTIVE'?'is-active':''}>{selectedEmployee.status==='ACTIVE'?copy.activeStatus:copy.inactiveStatus}</em></section><section className="employeeDetailStats"><div><strong>{selectedEmployee.summary?.totalHours||'0.00'} h</strong><span>{copy.week}</span></div><div><strong>{selectedEmployee.pendingSubmissions||0}</strong><span>{copy.pending}</span></div></section><section className="employeeDetailSection"><h3>{copy.employeeDetails}</h3><label className="employeesField"><span>{copy.rate}</span><div className="employeeRateRow"><input inputMode="decimal" type="number" min="0" step="0.01" value={rateDraft} onChange={e=>setRateDraft(e.target.value)}/><button type="button" disabled={isMutating} onClick={saveRate}>{copy.saveRate}</button></div></label></section>{actionError?<p className="statusNote is-error">{actionError}</p>:null}{actionSuccess?<p className="statusNote is-success">{actionSuccess}</p>:null}<section className="employeeDetailSection"><h3>{copy.actions}</h3><button className="employeeAction" type="button" onClick={()=>{setResetPassword('');setModal('password')}}>{copy.resetPassword}<span>›</span></button><button className={`employeeAction ${selectedEmployee.status==='ACTIVE'?'is-danger':'is-success'}`} type="button" disabled={isMutating} onClick={toggleEmployeeStatus}>{selectedEmployee.status==='ACTIVE'?copy.deactivate:copy.reactivate}<span>›</span></button></section></div>:null}
      {modal==='password'&&selectedEmployee?<form className="employeesModalBody" onSubmit={submitPasswordReset}><p className="employeesModalCopy">{copy.resetCopy}</p><label className="employeesField"><span>{copy.newTemporaryPassword}</span><input type="password" minLength={8} value={resetPassword} placeholder={copy.minPlaceholder} onChange={e=>setResetPassword(e.target.value)} required/></label>{actionError?<p className="statusNote is-error">{actionError}</p>:null}<button className="employeesPrimaryButton" disabled={isMutating||resetPassword.length<8}>{copy.setTemporaryPassword}</button><button className="employeesCancelButton" type="button" onClick={()=>setModal('manage')}>{copy.cancel}</button></form>:null}
    </section></div>:null}
  </section>;
}
