import { useEffect, useMemo, useRef, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useNavigate, useSearchParams } from 'react-router-dom';

import { baseApi } from '@shared/app/api/baseApi.js';
import { getApiErrorMessage } from '@shared/app/api/getApiErrorMessage.js';
import { BackButton } from '@shared/app/components/BackButton/BackButton.jsx';
import { useI18n } from '@shared/app/i18n/useI18n.js';
import { applicationServerKey, isIos, isStandalone, pushSupported } from '@shared/app/utils/push.js';
import { useChangePasswordMutation, useDeleteMeMutation, useLogoutMutation, useUpdateProfileMutation } from '@shared/features/auth/authApi.js';
import { clearSession as clearAuthSession, selectToken, selectUser, setSession } from '@shared/features/auth/authSlice.js';
import { clearSession as clearStoredSession, saveSession } from '@shared/features/auth/authStorage.js';
import {
  useDeletePushSubscriptionMutation,
  useGetPushSettingsQuery,
  useSavePushSubscriptionMutation,
} from '../../features/worktrack/worktrackApi.js';
import './ProfilePage.css';

const LANGUAGES = [{ code: 'cs', flag: '🇨🇿' }, { code: 'uk', flag: '🇺🇦' }, { code: 'en', flag: '🇬🇧' }];
const MAX_PHOTO_BYTES = 5 * 1024 * 1024;
const AVATAR_SIZE = 512;
const DETAIL_SECTIONS = ['personal', 'work', 'language', 'password', 'notifications', 'account'];
const UNSAVED_COPY={uk:'Є незбережені зміни. Вийти без збереження?',cs:'Máte neuložené změny. Odejít bez uložení?',en:'You have unsaved changes. Leave without saving?'};
const PUSH_COPY={
  uk:{title:'Сповіщення',menuCopy:'Push-сповіщення та важливі оновлення',enabled:'Push-сповіщення увімкнено на цьому пристрої.',disabled:'Отримуйте важливі повідомлення, навіть коли WorkTrack закритий.',enable:'Увімкнути сповіщення',disable:'Вимкнути сповіщення',working:'Зачекайте…',unsupported:'Цей браузер не підтримує push-сповіщення.',install:'На iPhone відкрийте WorkTrack з ярлика на Початковому екрані, щоб увімкнути push-сповіщення.',denied:'Доступ до сповіщень заблоковано. Дозвольте їх для WorkTrack у налаштуваннях iPhone.',error:'Не вдалося налаштувати push-сповіщення.'},
  cs:{title:'Oznámení',menuCopy:'Push oznámení a důležité aktualizace',enabled:'Push oznámení jsou na tomto zařízení zapnutá.',disabled:'Dostávejte důležitá oznámení, i když je WorkTrack zavřený.',enable:'Zapnout oznámení',disable:'Vypnout oznámení',working:'Čekejte…',unsupported:'Tento prohlížeč nepodporuje push oznámení.',install:'Na iPhonu otevřete WorkTrack z ikony na ploše, abyste mohli zapnout push oznámení.',denied:'Oznámení jsou zablokována. Povolte je pro WorkTrack v nastavení iPhonu.',error:'Push oznámení se nepodařilo nastavit.'},
  en:{title:'Notifications',menuCopy:'Push notifications and important updates',enabled:'Push notifications are enabled on this device.',disabled:'Receive important updates even when WorkTrack is closed.',enable:'Enable notifications',disable:'Disable notifications',working:'Please wait…',unsupported:'This browser does not support push notifications.',install:'On iPhone, open WorkTrack from its Home Screen icon to enable push notifications.',denied:'Notifications are blocked. Allow them for WorkTrack in iPhone settings.',error:'Could not configure push notifications.'},
};

function getName(user) { return user?.name || [user?.firstName, user?.lastName].filter(Boolean).join(' ') || user?.email || '-'; }
function initials(user) { return [user?.firstName, user?.lastName].filter(Boolean).map(v => v[0]).join('').slice(0, 2).toUpperCase() || getName(user).slice(0, 1).toUpperCase(); }
function CameraIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8.2 5.5 9.4 3.8h5.2l1.2 1.7H19a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7.5a2 2 0 0 1 2-2h3.2Z"/><circle cx="12" cy="12.5" r="3.4"/></svg>; }
function resizeProfilePhoto(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = reject; reader.onload = () => { const image = new Image(); image.onerror = reject; image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = AVATAR_SIZE; canvas.height = AVATAR_SIZE; const context = canvas.getContext('2d'); if (!context) { reject(new Error('Canvas is unavailable')); return; } const sourceSize = Math.min(image.naturalWidth, image.naturalHeight); const sourceX = Math.max(0, (image.naturalWidth - sourceSize) / 2); const sourceY = Math.max(0, (image.naturalHeight - sourceSize) / 2); context.drawImage(image, sourceX, sourceY, sourceSize, sourceSize, 0, 0, AVATAR_SIZE, AVATAR_SIZE); resolve(canvas.toDataURL('image/jpeg', 0.82)); }; image.src = String(reader.result || ''); }; reader.readAsDataURL(file); }); }

export function ProfilePage() {
  const dispatch = useDispatch(); const navigate = useNavigate(); const [searchParams] = useSearchParams(); const user = useSelector(selectUser); const token = useSelector(selectToken); const { language, setLanguage, t } = useI18n();
  const membership = user?.activeMembership || null; const isEmployee = membership?.role === 'EMPLOYEE'; const roleLabel = membership?.role === 'MANAGER' ? t('profile.manager') : isEmployee ? t('profile.employee') : '-'; const rate = membership?.hourlyRateCzk || '';
  const requestedSection = searchParams.get('section') || ''; const section = DETAIL_SECTIONS.includes(requestedSection) ? requestedSection : ''; const fromSettings = searchParams.get('from') === 'settings'; const backTo = fromSettings ? '/more' : '/profile'; const photoInputRef = useRef(null);
  const [updateProfile, profileState] = useUpdateProfileMutation(); const [firstName, setFirstName] = useState(user?.firstName || ''); const [lastName, setLastName] = useState(user?.lastName || ''); const [phone, setPhone] = useState(user?.phone || ''); const [avatarDraft, setAvatarDraft] = useState(user?.profile?.avatarDataUrl || ''); const [profileError, setProfileError] = useState(''); const [profileSuccess,setProfileSuccess]=useState('');
  const [changePassword, changeState] = useChangePasswordMutation(); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [passwordError, setPasswordError] = useState(''); const [passwordSuccess,setPasswordSuccess]=useState('');
  const [logout, logoutState] = useLogoutMutation(); const [deleteMe, deleteState] = useDeleteMeMutation(); const [deleteConfirmation, setDeleteConfirmation] = useState(''); const [accountError, setAccountError] = useState('');
  const canPush=pushSupported(); const pushCopy=PUSH_COPY[language]||PUSH_COPY.uk; const pushSettings=useGetPushSettingsQuery(undefined,{skip:!isEmployee||!canPush}); const [savePush,savePushState]=useSavePushSubscriptionMutation(); const [deletePush,deletePushState]=useDeletePushSubscriptionMutation(); const [pushEnabled,setPushEnabled]=useState(false); const [pushError,setPushError]=useState(''); const pushBusy=savePushState.isLoading||deletePushState.isLoading;
  const personalHasChanges=useMemo(()=>firstName.trim()!==String(user?.firstName||'').trim()||lastName.trim()!==String(user?.lastName||'').trim()||phone.trim()!==String(user?.phone||'').trim()||avatarDraft!==String(user?.profile?.avatarDataUrl||''),[firstName,lastName,phone,avatarDraft,user]);
  const passwordHasChanges=Boolean(currentPassword||newPassword||confirmPassword); const sectionDirty=section==='personal'?personalHasChanges:section==='password'?passwordHasChanges:false;

  useEffect(()=>{let active=true;if(!isEmployee||!canPush)return undefined;navigator.serviceWorker.getRegistration('/').then(async registration=>{const subscription=registration?await registration.pushManager.getSubscription():null;if(active)setPushEnabled(Boolean(subscription));}).catch(()=>{if(active)setPushEnabled(false);});return()=>{active=false;};},[isEmployee,canPush]);

  function applyUpdatedUser(updatedUser) { saveSession(token, updatedUser); dispatch(setSession({ token, user: updatedUser })); }
  function clearClientSession() { clearStoredSession(); dispatch(clearAuthSession()); dispatch(baseApi.util.resetApiState()); }
  function openSection(nextSection) { navigate(`/profile?section=${nextSection}`); }
  function goBack(){if(sectionDirty&&!window.confirm(UNSAVED_COPY[language]||UNSAVED_COPY.uk))return;navigate(backTo);}
  async function handlePhotoChange(event) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setProfileError(''); setProfileSuccess(''); if (file.size > MAX_PHOTO_BYTES) { setProfileError(t('profileUi.photoTooLarge')); return; } if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { setProfileError(t('profileUi.photoInvalid')); return; } try { setAvatarDraft(await resizeProfilePhoto(file)); } catch { setProfileError(t('profileUi.photoInvalid')); } }
  async function handleProfileSubmit(event) { event.preventDefault(); setProfileError(''); setProfileSuccess(''); const normalizedFirstName = firstName.trim(); if (!normalizedFirstName) { setProfileError(t('profile.firstNameRequired')); return; } try { const updatedUser = await updateProfile({ firstName: normalizedFirstName, lastName: lastName.trim(), name: [normalizedFirstName, lastName.trim()].filter(Boolean).join(' '), phone: phone.trim(), profile: { ...(user?.profile || {}), avatarDataUrl: avatarDraft || '' } }).unwrap(); applyUpdatedUser(updatedUser); setFirstName(updatedUser?.firstName||normalizedFirstName); setLastName(updatedUser?.lastName||lastName.trim()); setPhone(updatedUser?.phone||''); setAvatarDraft(updatedUser?.profile?.avatarDataUrl||''); setProfileSuccess(`✓ ${t('profile.profileUpdated')}`); } catch (error) { setProfileError(getApiErrorMessage(error)); } }
  async function handlePasswordSubmit(event) { event.preventDefault(); setPasswordError(''); setPasswordSuccess(''); if (newPassword !== confirmPassword) { setPasswordError(t('profile.passwordsDoNotMatch')); return; } try { const updatedUser = await changePassword({ currentPassword, newPassword }).unwrap(); applyUpdatedUser(updatedUser); setCurrentPassword(''); setNewPassword(''); setConfirmPassword(''); setPasswordSuccess(`✓ ${t('profile.passwordUpdated')}`); } catch (error) { setPasswordError(getApiErrorMessage(error)); } }
  async function handleLogout() { setAccountError(''); try { await logout().unwrap(); clearClientSession(); navigate('/sign-in', { replace: true }); } catch (error) { setAccountError(getApiErrorMessage(error)); } }
  async function handleDeleteAccount() { if (deleteConfirmation.trim() !== 'DELETE') return; setAccountError(''); try { await deleteMe().unwrap(); clearClientSession(); navigate('/sign-in', { replace: true }); } catch (error) { setAccountError(getApiErrorMessage(error)); } }
  async function enablePush(){setPushError('');if(!canPush){setPushError(pushCopy.unsupported);return;}if(isIos()&&!isStandalone()){setPushError(pushCopy.install);return;}try{const permission=await Notification.requestPermission();if(permission!=='granted'){setPushError(pushCopy.denied);return;}const registration=await navigator.serviceWorker.register('/sw.js',{scope:'/'});await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(!subscription){const publicKey=pushSettings.data?.publicKey;if(!publicKey)throw new Error('Push key unavailable');subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:applicationServerKey(publicKey)});}await savePush(subscription.toJSON()).unwrap();setPushEnabled(true);await pushSettings.refetch();}catch(error){setPushError(getApiErrorMessage(error)||pushCopy.error);}}
  async function disablePush(){setPushError('');if(!canPush)return;try{const registration=await navigator.serviceWorker.getRegistration('/');const subscription=registration?await registration.pushManager.getSubscription():null;if(subscription){await deletePush({endpoint:subscription.endpoint}).unwrap();await subscription.unsubscribe();}setPushEnabled(false);await pushSettings.refetch();}catch(error){setPushError(getApiErrorMessage(error)||pushCopy.error);}}

  let pushStatus=pushEnabled?pushCopy.enabled:pushCopy.disabled;if(!canPush)pushStatus=pushCopy.unsupported;else if(isIos()&&!isStandalone())pushStatus=pushCopy.install;else if(Notification.permission==='denied')pushStatus=pushCopy.denied;
  const languageName = t(`settings.languageCard.${language}`); const avatar = user?.profile?.avatarDataUrl || ''; const detailTitle = section === 'personal' ? t('profileUi.editPersonal') : section === 'work' ? t('profileUi.work') : section === 'language' ? t('profileUi.language') : section === 'password' ? t('profileUi.changePassword') : section === 'notifications' ? pushCopy.title : t('profileUi.danger');
  if (section) return <section className="profilePage profileDetailPage pageStack"><header className="profileDetailHeader appTop"><BackButton onClick={goBack}/><div className="appTitleBlock"><h1>{detailTitle}</h1></div></header><section className="profileDetailCard screenCard">
    {section === 'personal' ? <form onSubmit={handleProfileSubmit} className="profileDetailBody"><div className="profilePhotoEditor"><button className={`profilePhotoButton${avatarDraft ? ' has-photo' : ''}`} type="button" onClick={() => photoInputRef.current?.click()} aria-label={t('profileUi.photoHint')}>{avatarDraft ? <img src={avatarDraft} alt="" /> : <span>{initials(user)}</span>}<i aria-hidden="true"><CameraIcon /></i></button><input ref={photoInputRef} className="profilePhotoInput" type="file" accept="image/jpeg,image/png,image/webp" onChange={handlePhotoChange} /><p>{t('profileUi.photoHint')}</p><small>{t('profileUi.photoRules')}</small></div><div className="profileFieldGrid"><label className="profileField"><span>{t('profile.firstName')}</span><input type="text" value={firstName} onChange={e => {setFirstName(e.target.value);setProfileSuccess('');}} required /></label><label className="profileField"><span>{t('profile.lastName')}</span><input type="text" value={lastName} onChange={e => {setLastName(e.target.value);setProfileSuccess('');}} /></label></div><label className="profileField"><span>{t('profile.phone')}</span><input type="tel" autoComplete="tel" placeholder="+420 777 123 456" value={phone} onChange={e => {setPhone(e.target.value);setProfileSuccess('');}} /></label>{profileSuccess ? <p className="statusNote is-success">{profileSuccess}</p> : null}{profileError ? <p className="statusNote is-error">{profileError}</p> : null}<button className="profilePrimaryButton" disabled={profileState.isLoading||!personalHasChanges}>{profileState.isLoading ? t('profile.saving') : personalHasChanges?t('profileUi.save'):t('company.saved')}</button></form> : null}
    {section === 'work' ? <div className="profileDetailBody profileInfoList"><div><span>{t('profileUi.email')}</span><strong>{user?.email || '-'}</strong></div><div><span>{t('profileUi.role')}</span><strong>{roleLabel}</strong></div><div><span>{t('profileUi.company')}</span><strong>{user?.activeCompany?.name || '-'}</strong></div><div><span>{t('profileUi.hourlyRate')}</span><strong>{rate ? `${rate} CZK` : '-'}</strong></div></div> : null}
    {section === 'language' ? <div className="profileDetailBody languagePicker">{LANGUAGES.map(item => <button key={item.code} className={`languageOption${language === item.code ? ' is-active' : ''}`} type="button" onClick={() => { setLanguage(item.code); navigate(backTo); }}><span>{item.flag}</span><span>{t(`settings.languageCard.${item.code}`)}</span><b>{language === item.code ? '✓' : ''}</b></button>)}</div> : null}
    {section === 'password' ? <form onSubmit={handlePasswordSubmit} className="profileDetailBody"><label className="profileField"><span>{t('profile.currentPassword')}</span><input type="password" value={currentPassword} onChange={e => {setCurrentPassword(e.target.value);setPasswordSuccess('');}} required /></label><label className="profileField"><span>{t('profile.newPassword')}</span><input type="password" value={newPassword} onChange={e => {setNewPassword(e.target.value);setPasswordSuccess('');}} required /></label><label className="profileField"><span>{t('profile.confirmPassword')}</span><input type="password" value={confirmPassword} onChange={e => {setConfirmPassword(e.target.value);setPasswordSuccess('');}} required /></label>{passwordSuccess ? <p className="statusNote is-success">{passwordSuccess}</p> : null}{passwordError ? <p className="statusNote is-error">{passwordError}</p> : null}<button className="profilePrimaryButton" disabled={changeState.isLoading||!passwordHasChanges}>{changeState.isLoading ? t('profile.saving') : passwordHasChanges?t('profile.updatePassword'):t('company.saved')}</button></form> : null}
    {section === 'notifications' && isEmployee ? <div className="profileDetailBody"><div className="profileInfoList"><div><span>{pushCopy.title}</span><strong>{pushEnabled ? '✓' : '—'}</strong></div></div><p className={pushError ? 'statusNote is-error' : 'profileDangerCopy'}>{pushError || pushStatus}</p><button className="profilePrimaryButton" type="button" onClick={pushEnabled?disablePush:enablePush} disabled={pushBusy||pushSettings.isLoading||!canPush}>{pushBusy?pushCopy.working:pushEnabled?pushCopy.disable:pushCopy.enable}</button></div> : null}
    {section === 'account' ? <div className="profileDetailBody">{accountError ? <p className="statusNote is-error">{accountError}</p> : null}<div className="profileDangerZone profileDangerZoneOnly"><p className="profileDangerCopy">{t('profileUi.deleteCopy')}</p><label className="profileField"><span>{t('profileUi.deleteHint')}</span><input value={deleteConfirmation} onChange={e => setDeleteConfirmation(e.target.value)} placeholder="DELETE" /></label><button className="profileDangerButton" type="button" disabled={deleteState.isLoading || deleteConfirmation.trim() !== 'DELETE'} onClick={handleDeleteAccount}>{deleteState.isLoading ? t('profile.deleting') : t('profileUi.deleteAccount')}</button></div></div> : null}
  </section></section>;

  return <section className="profilePage pageStack"><header className="profileHero screenCard"><div className={`profileAvatar${avatar ? ' has-photo' : ''}`}>{avatar ? <img src={avatar} alt="" /> : initials(user)}</div><div><p className="sectionEyebrow">{t('profileUi.account')}</p><h1>{getName(user)}</h1><p>{roleLabel} · {user?.activeCompany?.name || '-'}</p></div></header>{user?.mustChangePassword ? <button className="profileNotice" type="button" onClick={() => openSection('password')}><strong>{t('profile.changeTemporaryPassword')}</strong><span>{t('profile.temporaryPasswordCopy')}</span><b>›</b></button> : null}<div className="profileGroups"><section><h2>{t('profileUi.account')}</h2><div className="profileMenu screenCard"><button type="button" onClick={() => openSection('personal')}><span className="profileMenuIcon">👤</span><span><strong>{t('profileUi.personal')}</strong><small>{t('profileUi.personalCopy')}</small></span><b>›</b></button><button type="button" onClick={() => openSection('work')}><span className="profileMenuIcon">💼</span><span><strong>{t('profileUi.work')}</strong><small>{t('profileUi.workCopy')}</small></span><b>›</b></button></div></section><section><h2>{t('profileUi.preferences')}</h2><div className="profileMenu screenCard"><button type="button" onClick={() => openSection('language')}><span className="profileMenuIcon">🌐</span><span><strong>{t('profileUi.language')}</strong><small>{languageName}</small></span><b>›</b></button><button type="button" onClick={() => openSection('password')}><span className="profileMenuIcon">🔒</span><span><strong>{t('profileUi.security')}</strong><small>{t('profileUi.securityCopy')}</small></span><b>›</b></button>{isEmployee ? <button type="button" onClick={() => openSection('notifications')}><span className="profileMenuIcon">🔔</span><span><strong>{pushCopy.title}</strong><small>{pushCopy.menuCopy}</small></span><b>›</b></button> : null}{isEmployee ? <button type="button" onClick={() => navigate('/tax-information')}><span className="profileMenuIcon">🧾</span><span><strong>{t('profileUi.tax')}</strong><small>{t('profileUi.taxCopy')}</small></span><b>›</b></button> : null}</div></section></div><button className="profileSignOut" type="button" disabled={logoutState.isLoading} onClick={handleLogout}>{logoutState.isLoading ? t('profile.signingOut') : t('profileUi.signOut')}</button><button className="profileAccountLink" type="button" onClick={() => openSection('account')}>{t('profileUi.danger')}</button></section>;
}