import { randomUUID } from 'node:crypto';
import { requireEmployee, requireManager } from '../auth/context.js';
import { runStoreRead, runStoreTransaction } from '../db/store.js';
import { readJsonBody, sendJson } from '../lib/http.js';
import { getEmployeeMonthlyHours } from '../services/monthly-hours.js';
import { createNotification } from '../services/notifications.js';
import {
  cancelInvoice,
  createInvoiceDraft,
  getEmployeeInvoice,
  getManagerInvoice,
  listEmployeeInvoices,
  listManagerInvoices,
  markInvoiceViewed,
  previewInvoiceDraft,
  sendInvoice,
} from '../services/invoices.js';

function clean(value,maxLength=180){return String(value??'').trim().slice(0,maxLength)}
function normalizeTaxInformation(body={}){const dueDays=Math.min(90,Math.max(1,Number.parseInt(body.dueDays,10)||14));return{businessName:clean(body.businessName,160),ico:clean(body.ico,32),dic:clean(body.dic,40),address:clean(body.address,300),iban:clean(body.iban,80),currency:'CZK',dueDays,prefix:clean(body.prefix,16).toUpperCase()||'WT'}}
function readTaxInformation(user){const profile=user?.profile&&typeof user.profile==='object'&&!Array.isArray(user.profile)?user.profile:{};return normalizeTaxInformation(profile.taxInformation||{})}
function normalizeCompanyBilling(body={}){return{ico:clean(body.ico,32),dic:clean(body.dic,40),address:clean(body.address,300),email:clean(body.email,160)}}
function paymentDate(value){const raw=clean(value,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(raw))throw new Error('Invalid payment date');const parsed=new Date(`${raw}T12:00:00.000Z`);if(Number.isNaN(parsed.getTime())||parsed.toISOString().slice(0,10)!==raw)throw new Error('Invalid payment date');const today=new Date();today.setUTCHours(23,59,59,999);if(parsed>today)throw new Error('Payment date cannot be in the future');return parsed}

async function auditInvoice(client,context,action,invoice,beforeStatus=null){
 if(!invoice?.id)return;
 await client.auditLog.create({data:{id:randomUUID(),action,actorUserId:context?.user?.id||null,entityType:'Invoice',entityId:invoice.id,before:beforeStatus?{status:beforeStatus}:null,after:{status:invoice.status,invoiceNumber:invoice.invoiceNumber,subtotal:invoice.subtotal,currency:invoice.currency,paidAt:invoice.paidAt||null},meta:{companyId:invoice.companyId,employeeMembershipId:invoice.employeeMembershipId}}});
}
async function invoiceHistory(client,invoiceId){
 const rows=await client.auditLog.findMany({where:{entityType:'Invoice',entityId:invoiceId},orderBy:{createdAt:'asc'}});
 return rows.map(row=>({id:row.id,action:row.action,before:row.before||null,after:row.after||null,createdAt:row.createdAt.toISOString()}));
}
async function employeeOwnsInvoice(client,context,invoiceId){return client.invoice.findFirst({where:{id:invoiceId,companyId:context.activeMembership.companyId,employeeMembershipId:context.activeMembership.id},select:{id:true}})}
async function managerCanSeeInvoice(client,context,invoiceId){return client.invoice.findFirst({where:{id:invoiceId,companyId:context.activeMembership.companyId,status:{not:'DRAFT'}},select:{id:true}})}

async function notifyManagersInvoiceSent(client,context,invoice){const managers=await client.companyMembership.findMany({where:{companyId:context.activeMembership.companyId,id:{not:context.activeMembership.id},role:'MANAGER',status:'ACTIVE'},select:{id:true}});await Promise.all(managers.map(manager=>createNotification(client,{companyId:context.activeMembership.companyId,recipientMembershipId:manager.id,type:'invoice.sent',title:`Invoice ${invoice.invoiceNumber} received`,message:`${invoice.totalHours} h · ${invoice.subtotal} ${invoice.currency}`,href:'/manager/invoices'})))}
async function notifyManagersInvoiceCancelled(client,context,invoice){const managers=await client.companyMembership.findMany({where:{companyId:context.activeMembership.companyId,id:{not:context.activeMembership.id},role:'MANAGER',status:'ACTIVE'},select:{id:true}});await Promise.all(managers.map(manager=>createNotification(client,{companyId:context.activeMembership.companyId,recipientMembershipId:manager.id,type:'invoice.cancelled',title:`Invoice ${invoice.invoiceNumber} cancelled`,message:'The employee cancelled this invoice.',href:'/manager/invoices'})))}
async function notifyEmployeeInvoiceViewed(client,context,invoice){await createNotification(client,{companyId:context.activeMembership.companyId,recipientMembershipId:invoice.employeeMembershipId,type:'invoice.viewed',title:`Invoice ${invoice.invoiceNumber} viewed`,message:'Your employer opened the invoice.',href:'/invoices'})}
async function notifyEmployeeInvoicePaid(client,context,invoice){await createNotification(client,{companyId:context.activeMembership.companyId,recipientMembershipId:invoice.employeeMembershipId,type:'invoice.paid',title:`Invoice ${invoice.invoiceNumber} paid`,message:`${invoice.subtotal} ${invoice.currency} was marked as paid.`,href:'/invoices'})}

export async function handleBillingRoutes(request,response,{pathName,url}){
 if(request.method==='GET'&&pathName==='/api/tax-information'){const context=await requireEmployee(request,response);if(!context)return true;sendJson(response,200,{taxInformation:readTaxInformation(context.user)});return true}
 if(request.method==='PATCH'&&pathName==='/api/tax-information'){const context=await requireEmployee(request,response);if(!context)return true;const body=await readJsonBody(request);const taxInformation=normalizeTaxInformation(body);const updatedUser=await runStoreTransaction({prisma:async client=>{const current=await client.user.findUnique({where:{id:context.user.id},select:{profile:true}});const profile=current?.profile&&typeof current.profile==='object'&&!Array.isArray(current.profile)?current.profile:{};return client.user.update({where:{id:context.user.id},data:{profile:{...profile,taxInformation}},select:{id:true,profile:true,updatedAt:true}})}});sendJson(response,200,{taxInformation,updatedAt:updatedUser.updatedAt});return true}
 if(request.method==='GET'&&pathName==='/api/company-billing'){const context=await requireManager(request,response);if(!context)return true;const company=await runStoreRead({prisma:client=>client.company.findUnique({where:{id:context.activeMembership.companyId},select:{id:true,name:true,billingProfile:true}})});sendJson(response,200,{company:{...company,billingProfile:normalizeCompanyBilling(company?.billingProfile||{})}});return true}
 if(request.method==='PATCH'&&pathName==='/api/company-billing'){const context=await requireManager(request,response);if(!context)return true;const billingProfile=normalizeCompanyBilling(await readJsonBody(request));const company=await runStoreTransaction({prisma:client=>client.company.update({where:{id:context.activeMembership.companyId},data:{billingProfile},select:{id:true,name:true,billingProfile:true}})});sendJson(response,200,{company});return true}
 if(request.method==='GET'&&pathName==='/api/monthly-hours'){const context=await requireEmployee(request,response);if(!context)return true;const payload=await runStoreRead({prisma:client=>getEmployeeMonthlyHours(client,context,url.searchParams.get('month'))});sendJson(response,200,payload);return true}
 if(request.method==='GET'&&pathName==='/api/invoices/preview'){const context=await requireEmployee(request,response);if(!context)return true;const preview=await runStoreRead({prisma:client=>previewInvoiceDraft(client,context,{month:url.searchParams.get('month')})});sendJson(response,200,{preview});return true}
 const employeeHistoryMatch=pathName.match(/^\/api\/invoices\/([^/]+)\/history$/);if(request.method==='GET'&&employeeHistoryMatch){const context=await requireEmployee(request,response);if(!context)return true;const history=await runStoreRead({prisma:async client=>{if(!await employeeOwnsInvoice(client,context,employeeHistoryMatch[1]))throw new Error('Invoice not found');return invoiceHistory(client,employeeHistoryMatch[1])}});sendJson(response,200,{history});return true}
 const employeeDetailMatch=pathName.match(/^\/api\/invoices\/([^/]+)$/);if(request.method==='GET'&&employeeDetailMatch){const context=await requireEmployee(request,response);if(!context)return true;const invoice=await runStoreRead({prisma:client=>getEmployeeInvoice(client,context,employeeDetailMatch[1])});sendJson(response,200,{invoice});return true}
 if(request.method==='DELETE'&&employeeDetailMatch){const context=await requireEmployee(request,response);if(!context)return true;const result=await runStoreTransaction({prisma:async client=>{const invoice=await client.invoice.findFirst({where:{id:employeeDetailMatch[1],companyId:context.activeMembership.companyId,employeeMembershipId:context.activeMembership.id},select:{id:true,status:true,invoiceNumber:true}});if(!invoice)throw new Error('Invoice not found');if(invoice.status!=='DRAFT')throw new Error('Only draft invoices can be deleted');await client.invoice.delete({where:{id:invoice.id}});return{id:invoice.id,invoiceNumber:invoice.invoiceNumber}}});sendJson(response,200,{deleted:true,invoice:result});return true}
 if(request.method==='GET'&&pathName==='/api/invoices'){const context=await requireEmployee(request,response);if(!context)return true;const payload=await runStoreRead({prisma:client=>listEmployeeInvoices(client,context)});sendJson(response,200,payload);return true}
 if(request.method==='POST'&&pathName==='/api/invoices'){const context=await requireEmployee(request,response);if(!context)return true;const body=await readJsonBody(request);const invoice=await runStoreTransaction({prisma:async client=>{const result=await createInvoiceDraft(client,context,body);await auditInvoice(client,context,'invoice.created',result);return result}});sendJson(response,201,{invoice});return true}
 const sendMatch=pathName.match(/^\/api\/invoices\/([^/]+)\/send$/);if(request.method==='POST'&&sendMatch){const context=await requireEmployee(request,response);if(!context)return true;const invoice=await runStoreTransaction({prisma:async client=>{const result=await sendInvoice(client,context,sendMatch[1]);await auditInvoice(client,context,'invoice.sent',result,'DRAFT');await notifyManagersInvoiceSent(client,context,result);return result}});sendJson(response,200,{invoice});return true}
 const cancelMatch=pathName.match(/^\/api\/invoices\/([^/]+)\/cancel$/);if(request.method==='POST'&&cancelMatch){const context=await requireEmployee(request,response);if(!context)return true;const invoice=await runStoreTransaction({prisma:async client=>{const before=await client.invoice.findFirst({where:{id:cancelMatch[1],companyId:context.activeMembership.companyId,employeeMembershipId:context.activeMembership.id},select:{status:true}});const result=await cancelInvoice(client,context,cancelMatch[1]);await auditInvoice(client,context,'invoice.cancelled',result,before?.status||null);if(result.sentAt)await notifyManagersInvoiceCancelled(client,context,result);return result}});sendJson(response,200,{invoice});return true}
 const managerHistoryMatch=pathName.match(/^\/api\/manager\/invoices\/([^/]+)\/history$/);if(request.method==='GET'&&managerHistoryMatch){const context=await requireManager(request,response);if(!context)return true;const history=await runStoreRead({prisma:async client=>{if(!await managerCanSeeInvoice(client,context,managerHistoryMatch[1]))throw new Error('Invoice not found');return invoiceHistory(client,managerHistoryMatch[1])}});sendJson(response,200,{history});return true}
 const managerDetailMatch=pathName.match(/^\/api\/manager\/invoices\/([^/]+)$/);if(request.method==='GET'&&managerDetailMatch){const context=await requireManager(request,response);if(!context)return true;const invoice=await runStoreRead({prisma:client=>getManagerInvoice(client,context,managerDetailMatch[1])});sendJson(response,200,{invoice});return true}
 if(request.method==='GET'&&pathName==='/api/manager/invoices'){const context=await requireManager(request,response);if(!context)return true;const payload=await runStoreRead({prisma:client=>listManagerInvoices(client,context)});sendJson(response,200,payload);return true}
 const viewedMatch=pathName.match(/^\/api\/manager\/invoices\/([^/]+)\/viewed$/);if(request.method==='POST'&&viewedMatch){const context=await requireManager(request,response);if(!context)return true;const invoice=await runStoreTransaction({prisma:async client=>{const before=await client.invoice.findFirst({where:{id:viewedMatch[1],companyId:context.activeMembership.companyId},select:{status:true}});const result=await markInvoiceViewed(client,context,viewedMatch[1]);if(before?.status==='SENT'){await auditInvoice(client,context,'invoice.viewed',result,'SENT');await notifyEmployeeInvoiceViewed(client,context,result)}return result}});sendJson(response,200,{invoice});return true}
 const paidMatch=pathName.match(/^\/api\/manager\/invoices\/([^/]+)\/paid$/);if(request.method==='POST'&&paidMatch){const context=await requireManager(request,response);if(!context)return true;const body=await readJsonBody(request);const paidAt=paymentDate(body.paidDate);const invoice=await runStoreTransaction({prisma:async client=>{const current=await client.invoice.findFirst({where:{id:paidMatch[1],companyId:context.activeMembership.companyId},select:{id:true,status:true}});if(!current)throw new Error('Invoice not found');if(!['SENT','VIEWED'].includes(current.status))throw new Error('Invoice cannot be marked paid');await client.invoice.update({where:{id:current.id},data:{status:'PAID',paidAt}});const result=await getManagerInvoice(client,context,current.id);await auditInvoice(client,context,'invoice.paid',result,current.status);await notifyEmployeeInvoicePaid(client,context,result);return result}});sendJson(response,200,{invoice});return true}
 return false;
}
