import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';

import { baseApi } from '@shared/app/api/baseApi.js';
import { SvgIcon } from '@shared/app/components/SvgIcon/SvgIcon.jsx';
import { useI18n } from '@shared/app/i18n/useI18n.js';
import { hasManagerAccess } from '@shared/features/auth/authAccess.js';
import { useDeleteMeMutation, useLogoutMutation } from '@shared/features/auth/authApi.js';
import { clearSession as clearAuthSession, selectUser } from '@shared/features/auth/authSlice.js';
import { clearSession as clearStoredSession } from '@shared/features/auth/authStorage.js';
import { setCabinetMode, useCabinetMode } from '@shared/features/auth/cabinetMode.js';
import './MoreHubPage.css';

const COPY = {
  uk: { title:'Налаштування',copy:'Компанія, робота та ваш акаунт.',companyGroup:'Компанія',identity:'Дані компанії',identityCopy:'Назва та системні дані',billing:'Реквізити',billingCopy:'IČO, DIČ, адреса та email для фактур',workGroup:'Робота',work:'Робочі правила',workCopy:'Обід, денна норма та графік роботи',myWork:'Моя робота',myWorkCopy:'Ставка, правила та дані компанії',employeeCabinet:'Кабінет працівника',employeeCabinetCopy:'Мої години, зарплата та фактури',managerCabinet:'Кабінет менеджера',managerCabinetCopy:'Команда, табель, погодження та фінанси',accountGroup:'Акаунт',personal:'Особисті дані',notifications:'Сповіщення',notificationsCopy:'Push-сповіщення на цьому пристрої',languageCopy:'Мова інтерфейсу застосунку',securityCopy:'Оновити пароль для входу',tax:'Податкова інформація',taxCopy:'Дані для автоматичного створення фактур',securityGroup:'Безпека',logout:'Вийти з акаунта',logoutCopy:'Завершити поточний сеанс',logoutTitle:'Вийти з акаунта?',logoutConfirm:'Вийти',logoutConfirmCopy:'Ви зможете увійти знову у будь-який момент.',logoutError:'Не вдалося вийти. Спробуйте ще раз.',deleteAccount:'Видалити акаунт',deleteAccountCopy:'Повністю видалити ваш акаунт',deleteTitle:'Видалити акаунт?',deleteConfirm:'Видалити акаунт',deleteConfirmCopy:'Цю дію неможливо скасувати. Ваш акаунт і пов’язані з ним особисті дані буде видалено.',deleteError:'Не вдалося видалити акаунт. Спробуйте ще раз.',cancel:'Скасувати',version:'Версія' },
  cs: { title:'Nastavení',copy:'Společnost, práce a váš účet.',companyGroup:'Společnost',identity:'Údaje společnosti',identityCopy:'Název a systémové údaje',billing:'Fakturační údaje',billingCopy:'IČO, DIČ, adresa a e-mail pro faktury',workGroup:'Práce',work:'Pracovní pravidla',workCopy:'Přestávka, denní norma a pracovní plán',myWork:'Moje práce',myWorkCopy:'Sazba, pravidla a údaje společnosti',employeeCabinet:'Kabinet pracovníka',employeeCabinetCopy:'Moje hodiny, mzda a faktury',managerCabinet:'Kabinet manažera',managerCabinetCopy:'Tým, výkazy, schválení a finance',accountGroup:'Účet',personal:'Osobní údaje',notifications:'Oznámení',notificationsCopy:'Push oznámení na tomto zařízení',languageCopy:'Jazyk rozhraní aplikace',securityCopy:'Aktualizovat přihlašovací heslo',tax:'Daňové údaje',taxCopy:'Údaje pro automatické vystavování faktur',securityGroup:'Zabezpečení',logout:'Odhlásit se',logoutCopy:'Ukončit aktuální relaci',logoutTitle:'Odhlásit se?',logoutConfirm:'Odhlásit se',logoutConfirmCopy:'Kdykoli se můžete znovu přihlásit.',logoutError:'Odhlášení se nezdařilo. Zkuste to znovu.',deleteAccount:'Smazat účet',deleteAccountCopy:'Trvale smazat váš účet',deleteTitle:'Smazat účet?',deleteConfirm:'Smazat účet',deleteConfirmCopy:'Tuto akci nelze vrátit zpět. Váš účet a související osobní údaje budou smazány.',deleteError:'Účet se nepodařilo smazat. Zkuste to znovu.',cancel:'Zrušit',version:'Verze' },
  en: { title:'Settings',copy:'Company, work and your account.',companyGroup:'Company',identity:'Company details',identityCopy:'Name and system details',billing:'Billing details',billingCopy:'Company ID, VAT ID, address and invoice email',workGroup:'Work',work:'Work rules',workCopy:'Lunch, daily standard and work schedule',myWork:'My work',myWorkCopy:'Rate, rules and company details',employeeCabinet:'Employee workspace',employeeCabinetCopy:'My hours, salary and invoices',managerCabinet:'Manager workspace',managerCabinetCopy:'Team, timesheets, approvals and finances',accountGroup:'Account',personal:'Personal details',notifications:'Notifications',notificationsCopy:'Push notifications on this device',languageCopy:'Application interface language',securityCopy:'Update your sign-in password',tax:'Tax information',taxCopy:'Details used to create invoices automatically',securityGroup:'Security',logout:'Sign out',logoutCopy:'End the current session',logoutTitle:'Sign out?',logoutConfirm:'Sign out',logoutConfirmCopy:'You can sign back in at any time.',logoutError:'Could not sign out. Please try again.',deleteAccount:'Delete account',deleteAccountCopy:'Permanently delete your account',deleteTitle:'Delete account?',deleteConfirm:'Delete account',deleteConfirmCopy:'This action cannot be undone. Your account and associated personal data will be deleted.',deleteError:'Could not delete the account. Please try again.',cancel:'Cancel',version:'Version' },
};

function getName(user){return user?.name||[user?.firstName,user?.lastName].filter(Boolean).join(' ')||user?.email||'-'}
function getCompanyName(user){return user?.activeMembership?.company?.name||user?.activeCompany?.name||user?.company?.name||''}
function initials(user){return [user?.firstName,user?.lastName].filter(Boolean).map(value=>value[0]).join('').slice(0,2).toUpperCase()||getName(user).slice(0,1).toUpperCase()}
function SettingsRow({to,icon,title,copy,tone='default'}){return <Link to={to} className={`moreHubRow moreHubRow--${tone}`}><span className="moreHubIcon"><SvgIcon name={icon}/></span><span className="moreHubRowText"><strong>{title}</strong><small>{copy}</small></span><span className="moreHubChevron" aria-hidden="true">›</span></Link>}
function SettingsActionRow({onClick,icon,title,copy,tone='default',disabled=false}){return <button type="button" onClick={onClick} disabled={disabled} className={`moreHubRow moreHubRowButton moreHubRow--${tone}`}><span className="moreHubIcon"><SvgIcon name={icon}/></span><span className="moreHubRowText"><strong>{title}</strong><small>{copy}</small></span><span className="moreHubChevron" aria-hidden="true">›</span></button>}
function SettingsGroup({title,children,tone='default'}){return <section className={`moreHubGroup moreHubGroup--${tone}`}><h2>{title}</h2><div className="moreHubMenu">{children}</div></section>}

export function MoreHubPage(){
 const dispatch=useDispatch();const navigate=useNavigate();const user=useSelector(selectUser);const {language,t}=useI18n();const c=COPY[language]||COPY.uk;const cabinetMode=useCabinetMode(user);const managerCabinet=cabinetMode==='manager';const canSwitchCabinet=hasManagerAccess(user);const avatar=user?.profile?.avatarDataUrl||'';const companyName=getCompanyName(user);const roleLabel=managerCabinet?t('profile.manager'):t('profile.employee');const [logout,logoutState]=useLogoutMutation();const [deleteMe,deleteState]=useDeleteMeMutation();const [confirmAction,setConfirmAction]=useState('');const [actionError,setActionError]=useState('');
 const switchCabinet=()=>{const nextMode=managerCabinet?'employee':'manager';if(!setCabinetMode(nextMode,user))return;dispatch(baseApi.util.resetApiState());navigate('/',{replace:true});};
 const clearClientSession=()=>{clearStoredSession();dispatch(clearAuthSession());dispatch(baseApi.util.resetApiState());};
 const openConfirm=action=>{setActionError('');setConfirmAction(action);};
 const closeConfirm=()=>{if(logoutState.isLoading||deleteState.isLoading)return;setConfirmAction('');setActionError('');};
 const handleConfirmedAction=async()=>{setActionError('');try{if(confirmAction==='delete'){await deleteMe().unwrap();}else{await logout().unwrap();}clearClientSession();navigate('/sign-in',{replace:true});}catch{setActionError(confirmAction==='delete'?c.deleteError:c.logoutError);}};
 const cabinetSwitchRow=canSwitchCabinet?<SettingsActionRow onClick={switchCabinet} icon="accounts" tone="work" title={managerCabinet?c.employeeCabinet:c.managerCabinet} copy={managerCabinet?c.employeeCabinetCopy:c.managerCabinetCopy}/>:null;
 const confirmIsDelete=confirmAction==='delete';const confirmBusy=logoutState.isLoading||deleteState.isLoading;
 return <section className="moreHub pageStack">
  <header className="moreHubHeader appTop"><div className="appTitleBlock"><h1>{c.title}</h1><p>{c.copy}</p></div></header>
  <Link className="moreHubProfile moreHubProfile--link" to="/profile?section=personal&from=settings" aria-label={c.personal}><span className={`moreHubAvatar${avatar?' has-photo':''}`}>{avatar?<img src={avatar} alt=""/>:<span>{initials(user)}</span>} </span><span className="moreHubProfileMain"><span className="moreHubProfileText"><strong>{getName(user)}</strong><small>{user?.email||''}</small><span className="moreHubProfileMeta">{companyName?<span>{companyName}</span>:null}<em>{roleLabel}</em></span></span><span className="moreHubProfileChevron" aria-hidden="true">›</span></span></Link>
  {managerCabinet?<><SettingsGroup title={c.companyGroup}><SettingsRow to="/company-settings?section=identity&from=settings" icon="building" tone="company" title={c.identity} copy={c.identityCopy}/><SettingsRow to="/company-settings?section=billing&from=settings" icon="receipt" tone="billing" title={c.billing} copy={c.billingCopy}/></SettingsGroup><SettingsGroup title={c.workGroup}><SettingsRow to="/company-settings?section=work&from=settings" icon="clock" tone="work" title={c.work} copy={c.workCopy}/>{cabinetSwitchRow}</SettingsGroup></>:<SettingsGroup title={c.workGroup}><SettingsRow to="/profile?section=work&from=settings" icon="clock" tone="work" title={c.myWork} copy={c.myWorkCopy}/>{cabinetSwitchRow}</SettingsGroup>}
  <SettingsGroup title={c.accountGroup}><SettingsRow to="/notification-settings" icon="bell" tone="notifications" title={c.notifications} copy={c.notificationsCopy}/><SettingsRow to="/profile?section=language&from=settings" icon="globe" tone="language" title={t('settings.languageCard.title')} copy={c.languageCopy}/><SettingsRow to="/profile?section=password&from=settings" icon="lock" tone="security" title={t('profile.changePassword')} copy={c.securityCopy}/>{!managerCabinet?<SettingsRow to="/tax-information" icon="receipt" tone="billing" title={c.tax} copy={c.taxCopy}/>:null}</SettingsGroup>
  <SettingsGroup title={c.securityGroup} tone="danger"><SettingsActionRow onClick={()=>openConfirm('logout')} icon="logout" tone="danger" title={c.logout} copy={c.logoutCopy}/><SettingsActionRow onClick={()=>openConfirm('delete')} icon="trash" tone="dangerStrong" title={c.deleteAccount} copy={c.deleteAccountCopy}/></SettingsGroup>
  <p className="moreHubVersion">WorkTrack · {c.version} 1.0.0</p>
  {confirmAction?<div className="moreHubConfirmBackdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)closeConfirm();}}><section className={`moreHubConfirmSheet${confirmIsDelete?' is-delete':''}`} role="dialog" aria-modal="true" aria-labelledby="moreHubConfirmTitle"><div className="moreHubConfirmIcon"><SvgIcon name={confirmIsDelete?'trash':'logout'}/></div><div className="moreHubConfirmCopy"><h2 id="moreHubConfirmTitle">{confirmIsDelete?c.deleteTitle:c.logoutTitle}</h2><p>{confirmIsDelete?c.deleteConfirmCopy:c.logoutConfirmCopy}</p></div>{actionError?<p className="moreHubConfirmError">{actionError}</p>:null}<div className="moreHubConfirmActions"><button type="button" className="moreHubConfirmCancel" onClick={closeConfirm} disabled={confirmBusy}>{c.cancel}</button><button type="button" className={`moreHubConfirmPrimary${confirmIsDelete?' is-delete':''}`} onClick={handleConfirmedAction} disabled={confirmBusy}>{confirmBusy?'…':confirmIsDelete?c.deleteConfirm:c.logoutConfirm}</button></div></section></div>:null}
 </section>;
}
