import { useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { baseApi } from '@shared/app/api/baseApi.js';
import { getApiErrorMessage } from '@shared/app/api/getApiErrorMessage.js';
import { useI18n } from '@shared/app/i18n/useI18n.js';
import { SvgIcon } from '@shared/app/components/SvgIcon/SvgIcon.jsx';
import { useLogoutMutation, useUpdateProfileMutation } from '@shared/features/auth/authApi.js';
import { clearSession as clearAuthSession, selectToken, selectUser, setSession } from '@shared/features/auth/authSlice.js';
import { clearSession as clearStoredSession, saveSession } from '@shared/features/auth/authStorage.js';
import './MoreHubPage.css';

const MAX_PHOTO_BYTES = 5 * 1024 * 1024;
const AVATAR_SIZE = 512;

const COPY = {
  uk: { title:'Налаштування',copy:'Керуйте параметрами компанії та акаунта.',changePhoto:'Змінити фото',photoError:'Не вдалося змінити фото.',photoTooLarge:'Фото має бути до 5 МБ.',companyGroup:'Компанія',identity:'Дані компанії',identityCopy:'Назва, адреса та системні дані',billing:'Реквізити',billingCopy:'IČO, DIČ, адреса та email для рахунків',workGroup:'Робочі правила',work:'Робочі правила',workCopy:'Обід, денна норма та графік роботи',personal:'Особисті дані',accountGroup:'Акаунт',language:'Мова',languageCopy:'Мова інтерфейсу застосунку',security:'Змінити пароль',securityCopy:'Оновіть пароль для входу в акаунт',tax:'Податкова інформація',taxCopy:'Дані для автоматичного створення фактур',deleteAccount:'Видалити акаунт',deleteAccountCopy:'Назавжди видалити акаунт і доступ',signOut:'Вийти з акаунта',signingOut:'Вихід…',manager:'Менеджер',employee:'Працівник' },
  cs: { title:'Nastavení',copy:'Spravujte nastavení společnosti a účtu.',changePhoto:'Změnit fotografii',photoError:'Fotografii se nepodařilo změnit.',photoTooLarge:'Fotografie může mít nejvýše 5 MB.',companyGroup:'Společnost',identity:'Údaje společnosti',identityCopy:'Název, adresa a systémové údaje',billing:'Fakturační údaje',billingCopy:'IČO, DIČ, adresa a e-mail pro faktury',workGroup:'Pracovní pravidla',work:'Pracovní pravidla',workCopy:'Přestávka, denní norma a pracovní plán',personal:'Osobní údaje',accountGroup:'Účet',language:'Jazyk',languageCopy:'Jazyk rozhraní aplikace',security:'Změnit heslo',securityCopy:'Aktualizujte heslo pro přihlášení',tax:'Daňové údaje',taxCopy:'Údaje pro automatické vystavování faktur',deleteAccount:'Odstranit účet',deleteAccountCopy:'Trvale odstranit účet a přístup',signOut:'Odhlásit se',signingOut:'Odhlašování…',manager:'Manažer',employee:'Pracovník' },
  en: { title:'Settings',copy:'Manage company and account settings.',changePhoto:'Change photo',photoError:'Could not change photo.',photoTooLarge:'Photo must be under 5 MB.',companyGroup:'Company',identity:'Company details',identityCopy:'Name, address and system details',billing:'Billing details',billingCopy:'Company ID, VAT ID, address and invoice email',workGroup:'Work rules',work:'Work rules',workCopy:'Lunch, daily standard and work schedule',personal:'Personal details',accountGroup:'Account',language:'Language',languageCopy:'Application interface language',security:'Change password',securityCopy:'Update your account sign-in password',tax:'Tax information',taxCopy:'Details used to create invoices automatically',deleteAccount:'Delete account',deleteAccountCopy:'Permanently remove your account and access',signOut:'Sign out',signingOut:'Signing out…',manager:'Manager',employee:'Employee' },
};

function getName(user){return user?.name||[user?.firstName,user?.lastName].filter(Boolean).join(' ')||user?.email||'-'}
function getCompanyName(user){return user?.activeMembership?.company?.name||user?.activeCompany?.name||user?.company?.name||''}
function getRoleLabel(user,c){return user?.activeMembership?.role==='EMPLOYEE'?c.employee:c.manager}
function initials(user){return [user?.firstName,user?.lastName].filter(Boolean).map(value=>value[0]).join('').slice(0,2).toUpperCase()||getName(user).slice(0,1).toUpperCase()}
function resizeProfilePhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const image=new Image();image.onerror=reject;image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=AVATAR_SIZE;canvas.height=AVATAR_SIZE;const context=canvas.getContext('2d');if(!context)return reject(new Error('Canvas unavailable'));const size=Math.min(image.naturalWidth,image.naturalHeight);const x=Math.max(0,(image.naturalWidth-size)/2);const y=Math.max(0,(image.naturalHeight-size)/2);context.drawImage(image,x,y,size,size,0,0,AVATAR_SIZE,AVATAR_SIZE);resolve(canvas.toDataURL('image/jpeg',.82))};image.src=String(reader.result||'')};reader.readAsDataURL(file)})}
function SettingsRow({to,icon,title,copy,tone='default'}){return <Link to={to} className={`moreHubRow moreHubRow--${tone}`}><span className="moreHubIcon"><SvgIcon name={icon}/></span><span className="moreHubRowText"><strong>{title}</strong><small>{copy}</small></span><span className="moreHubChevron" aria-hidden="true">›</span></Link>}
function SettingsGroup({title,children}){return <section className="moreHubGroup"><h2>{title}</h2><div className="moreHubMenu screenCard">{children}</div></section>}

export function MoreHubPage(){
 const dispatch=useDispatch();const navigate=useNavigate();const user=useSelector(selectUser);const token=useSelector(selectToken);const {language}=useI18n();const c=COPY[language]||COPY.uk;const photoInputRef=useRef(null);const [updateProfile,updateState]=useUpdateProfileMutation();const [logout,logoutState]=useLogoutMutation();const [photoError,setPhotoError]=useState('');const [logoutError,setLogoutError]=useState('');const avatar=user?.profile?.avatarDataUrl||'';const companyName=getCompanyName(user);const roleLabel=getRoleLabel(user,c);const isEmployee=user?.activeMembership?.role==='EMPLOYEE';
 async function handlePhotoChange(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;setPhotoError('');if(file.size>MAX_PHOTO_BYTES){setPhotoError(c.photoTooLarge);return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setPhotoError(c.photoError);return}try{const avatarDataUrl=await resizeProfilePhoto(file);const updatedUser=await updateProfile({firstName:user?.firstName||'',lastName:user?.lastName||'',name:getName(user),phone:user?.phone||'',profile:{...(user?.profile||{}),avatarDataUrl}}).unwrap();saveSession(token,updatedUser);dispatch(setSession({token,user:updatedUser}))}catch{setPhotoError(c.photoError)}}
 async function handleLogout(){setLogoutError('');try{await logout().unwrap();clearStoredSession();dispatch(clearAuthSession());dispatch(baseApi.util.resetApiState());navigate('/sign-in',{replace:true})}catch(error){setLogoutError(getApiErrorMessage(error))}}
 return <section className="moreHub pageStack">
  <header className="moreHubHeader appTop"><div className="appTitleBlock"><h1>{c.title}</h1><p>{c.copy}</p></div></header>
  <section className="moreHubProfile screenCard"><button className={`moreHubAvatar${avatar?' has-photo':''}`} type="button" onClick={()=>photoInputRef.current?.click()} disabled={updateState.isLoading} aria-label={c.changePhoto}>{avatar?<img src={avatar} alt=""/>:<span>{initials(user)}</span>}<i aria-hidden="true"><SvgIcon name="edit"/></i></button><Link className="moreHubProfileMain" to="/profile?section=personal&from=settings" aria-label={c.personal}><span className="moreHubProfileText"><strong>{getName(user)}</strong><small>{user?.email||''}</small><em>{[companyName,roleLabel].filter(Boolean).join(' · ')}</em></span><span className="moreHubProfileChevron" aria-hidden="true">›</span></Link><button className="moreHubChangePhoto" type="button" onClick={()=>photoInputRef.current?.click()} disabled={updateState.isLoading}>{updateState.isLoading?'…':c.changePhoto}</button><input ref={photoInputRef} className="moreHubPhotoInput" type="file" accept="image/jpeg,image/png,image/webp" onChange={handlePhotoChange}/></section>
  {photoError?<p className="moreHubPhotoError">{photoError}</p>:null}
  {!isEmployee?<><SettingsGroup title={c.companyGroup}><SettingsRow to="/company-settings?section=identity&from=settings" icon="building" tone="company" title={c.identity} copy={c.identityCopy}/><SettingsRow to="/company-settings?section=billing&from=settings" icon="receipt" tone="billing" title={c.billing} copy={c.billingCopy}/></SettingsGroup><SettingsGroup title={c.workGroup}><SettingsRow to="/company-settings?section=work&from=settings" icon="clock" tone="work" title={c.work} copy={c.workCopy}/></SettingsGroup></>:null}
  <SettingsGroup title={c.accountGroup}><SettingsRow to="/profile?section=language&from=settings" icon="globe" tone="language" title={c.language} copy={c.languageCopy}/><SettingsRow to="/profile?section=password&from=settings" icon="lock" tone="security" title={c.security} copy={c.securityCopy}/>{isEmployee?<SettingsRow to="/tax-information" icon="receipt" tone="billing" title={c.tax} copy={c.taxCopy}/>:null}</SettingsGroup>
  <div className="moreHubAccountActions">{logoutError?<p className="moreHubLogoutError">{logoutError}</p>:null}<button className="moreHubSignOut" type="button" onClick={handleLogout} disabled={logoutState.isLoading}><SvgIcon name="logout"/><span>{logoutState.isLoading?c.signingOut:c.signOut}</span></button><Link className="moreHubDeleteAccount" to="/profile?section=account&from=settings"><SvgIcon name="trash"/><span><strong>{c.deleteAccount}</strong><small>{c.deleteAccountCopy}</small></span></Link></div>
 </section>;
}
