export const messages = {
  uk: {
    common: {
      failed: 'Не вдалося завантажити.',
      failedToLoad: 'Сторінку не вдалося відкрити. Спробуйте ще раз.',
      backToHome: 'Повернутися на головну',
      loading: 'Завантаження…',
      today: 'Сьогодні',
      previous: 'Назад',
      next: 'Далі',
      totalHours: 'Всього годин',
      approved: 'Погоджено',
      submitted: 'Відправлено',
      draft: 'Чернетка',
      rejected: 'Відхилено',
      overtime: 'Понаднормові',
      project: 'Проєкт',
      entries: 'записів',
    },
    app: { dashboard: 'Дашборд', hours: 'Години', employees: 'Працівники', approvals: 'Погодження', profile: 'Профіль' },
    auth: { email: 'E-mail', password: 'Пароль', login: 'Увійти', loginTitle: 'Вхід', loginFailed: 'Не вдалося увійти. Перевірте email і пароль.', loggingIn: 'Вхід...', showPassword: 'Показати пароль', hidePassword: 'Приховати пароль', sessionState: 'Сесія', sessionExpired: 'Сесію завершено', sessionExpiredSignIn: 'Увійдіть ще раз, щоб продовжити роботу.', connectionLostKeepSession: 'З’єднання втрачено. Сесію збережено, спробуйте ще раз.', sessionCheckFailedKeepSession: 'Не вдалося перевірити сесію. Спробуйте ще раз.', goToSignIn: 'Перейти до входу' },
    bottomTabs: { navLabel: 'Основна навігація' },
    guest: { titleLogin: 'Облік робочого часу', textLogin: 'Години, погодження та оплата в одному робочому просторі.', signInHeading: 'Увійдіть, щоб продовжити', signInCopy: 'Використовуйте email і пароль, щоб повернутися до свого простору.' },
    settings: { languageCard: { title: 'Мова', label: 'Мова інтерфейсу', description: 'Виберіть мову WorkTrack. Налаштування збережеться на цьому пристрої.', uk: 'Українська', en: 'English', cs: 'Čeština' } },
    profile: {
      title: 'Профіль', changeTemporaryPassword: 'Змініть тимчасовий пароль', temporaryPasswordCopy: 'Менеджер створив цей акаунт із тимчасовим паролем. Встановіть власний пароль.', email: 'E-mail', role: 'Роль', manager: 'Менеджер', employee: 'Працівник', company: 'Компанія', hourlyRate: 'Погодинна ставка', personalDetails: 'Особисті дані', personalDetailsCopy: 'Підтримуйте контактні дані в актуальному стані.', firstName: 'Ім’я', lastName: 'Прізвище', phone: 'Телефон', firstNameRequired: 'Ім’я є обов’язковим.', profileUpdated: 'Профіль успішно оновлено.', saving: 'Збереження…', saveProfile: 'Зберегти профіль', changePassword: 'Змінити пароль', passwordCopy: 'Використовуйте щонайменше 8 символів. Після зміни пароля інші активні сесії буде завершено.', currentPassword: 'Поточний пароль', newPassword: 'Новий пароль', confirmPassword: 'Підтвердіть новий пароль', passwordsDoNotMatch: 'Нові паролі не збігаються.', passwordUpdated: 'Пароль успішно оновлено.', updating: 'Оновлення…', updatePassword: 'Оновити пароль', accountSecurity: 'Акаунт і безпека', accountSecurityCopy: 'Вийдіть на цьому пристрої або назавжди видаліть свій акаунт WorkTrack.', signingOut: 'Вихід…', signOut: 'Вийти', deleteAccount: 'Видалити акаунт', deleteAccountCopy: 'Це завершить усі сесії та вимкне доступ до акаунта. Дію неможливо скасувати в застосунку.', typeDelete: 'Введіть DELETE для підтвердження', deleting: 'Видалення…'
    },
    dashboard: {
      myWorkspace: 'Мій робочий простір', companyWorkspace: 'Робочий простір компанії', goodMorning: 'Доброго ранку', goodAfternoon: 'Добрий день', goodEvening: 'Добрий вечір', managerIntro: 'Ось що відбувається у WorkTrack сьогодні.', employeeIntro: 'Ваші години, погодження та зарплата в одному місці.', loading: 'Завантаження дашборду', employees: 'Працівники', activeEmployees: 'Активні працівники', projects: 'Проєкти', activeProjects: 'Активні проєкти', pendingApprovals: 'Очікують погодження', weeksWaiting: 'Тижні в очікуванні', payroll: 'Зарплата', confirmedAmount: 'Підтверджена сума', thisWeek: 'Цього тижня', allSavedEntries: 'Усі збережені записи', pending: 'В очікуванні', draftOrSubmitted: 'Чернетки або відправлені', approved: 'Підтверджено', confirmedHours: 'Підтверджені години', salary: 'Зарплата', predicted: 'очікувано', needsAttention: 'Потребує вашої уваги', weekNeedsApproval: '{count} тиждень потребує погодження', weeksNeedApproval: '{count} тижнів потребують погодження', reviewSubmittedHours: 'Перевірте відправлені години до нарахування зарплати.', reviewApprovals: 'Перевірити погодження', confirmedSalary: 'Підтверджена зарплата', predictedFromPending: '{amount} очікується з непідтверджених годин.', viewPayroll: 'Переглянути зарплату', workspaceSummary: 'Огляд робочого простору', quickActions: 'Швидкі дії', managerQuickCopy: 'Перейдіть до розділів, якими користуєтесь найчастіше.', employeeQuickCopy: 'Керуйте та перевіряйте свій робочий час.', manageTeam: 'Керувати командою', viewWorksites: 'Переглянути об’єкти', payrollReport: 'Звіт по зарплаті', salaryOverview: 'Огляд зарплати', myHours: 'Мої години', addEditEntries: 'Додати або змінити записи', calendar: 'Календар', monthlyOverview: 'Огляд годин за місяць', pendingCount: '{count} в очікуванні', teamThisWeek: 'Команда цього тижня', teamSummary: '{notSubmitted} не відправили · {needsChanges} потребують змін', notSubmitted: 'Не відправлено', everyoneSubmitted: 'Усі вже відправили.', needsChanges: 'Потрібні зміни', noRejectedWeeks: 'Немає відхилених тижнів.', waitingReview: 'Очікують перевірки', nothingWaiting: 'Нічого не очікує перевірки.', approvedWeeks: 'Погоджено', noApprovedWeeks: 'Ще немає погоджених тижнів.'
    },
    calendar: {
      eyebrow: 'Історія роботи', title: 'Календар', intro: 'Переглядайте години, проєкти та статус погодження за кожен день.', navigation: 'Навігація календаря', previousMonth: 'Попередній місяць', nextMonth: 'Наступний місяць', monthSummary: 'Підсумок місяця', loading: 'Завантаження календаря', statusLegend: 'Позначення статусів', noHours: 'За цей день годин не записано.', workEntry: 'Робочий запис', addEntry: '+ Додати запис', openHours: 'Відкрити Мої години', overtimeSuffix: 'понаднормово'
    },
    approvals: {
      eyebrow: 'Простір менеджера', title: 'Погодження', intro: 'Перевіряйте відправлені робочі тижні та підтверджуйте години для нарахування зарплати.', pendingSummary: 'Підсумок очікуваних погоджень', pendingWeeks: 'Тижнів очікує', hoursWaiting: 'Годин очікує', loading: 'Завантаження погоджень', allCaughtUp: 'Усе перевірено', noPending: 'Немає відправлених тижнів, які очікують перевірки.', pending: 'Очікують', selectWeek: 'Виберіть тиждень, щоб переглянути записи.', pendingSubmissions: 'Відправлені тижні', submittedStatus: 'Відправлено', loadingDetails: 'Завантаження деталей', totalHours: 'Всього годин', workEntries: 'Робочі записи', decision: 'Рішення', decisionCopy: 'Погодьте тиждень або залиште чіткий коментар про те, що потрібно змінити.', rejectionReason: 'Причина відхилення', optionalUntilRejecting: 'необов’язково до відхилення', rejectionPlaceholder: 'Наприклад: виправте проєкт за п’ятницю та відправте тиждень повторно.', rejectWithNote: 'Відхилити з коментарем', approveWeek: 'Погодити тиждень', reasonRequired: 'Додайте причину перед відхиленням цього тижня.', employeeFallback: 'Працівник'
    }
  },
  en: {
    common: { failed: 'Failed to load.', failedToLoad: 'The page could not be opened. Please try again.', backToHome: 'Back to home', loading: 'Loading…', today: 'Today', previous: 'Previous', next: 'Next', totalHours: 'Total hours', approved: 'Approved', submitted: 'Submitted', draft: 'Draft', rejected: 'Rejected', overtime: 'Overtime', project: 'Project', entries: 'entries' },
    app: { dashboard: 'Dashboard', hours: 'Hours', employees: 'Employees', approvals: 'Approvals', profile: 'Profile' },
    auth: { email: 'Email', password: 'Password', login: 'Sign in', loginTitle: 'Sign in', loginFailed: 'Sign-in failed. Check your email and password.', loggingIn: 'Signing in...', showPassword: 'Show password', hidePassword: 'Hide password', sessionState: 'Session', sessionExpired: 'Session expired', sessionExpiredSignIn: 'Sign in again to continue working.', connectionLostKeepSession: 'Connection was lost. Your session is kept, try again.', sessionCheckFailedKeepSession: 'Session check failed. Try again.', goToSignIn: 'Go to sign in' },
    bottomTabs: { navLabel: 'Primary navigation' },
    guest: { titleLogin: 'Work hours tracking', textLogin: 'Hours, approvals, and payroll in one workspace.', signInHeading: 'Sign in to continue', signInCopy: 'Use your email and password to return to your workspace.' },
    settings: { languageCard: { title: 'Language', label: 'Interface language', description: 'Choose the WorkTrack language. Your choice is saved on this device.', uk: 'Українська', en: 'English', cs: 'Čeština' } },
    profile: {
      title: 'Profile', changeTemporaryPassword: 'Change your temporary password', temporaryPasswordCopy: 'Your manager created this account with a temporary password. Set your own password now.', email: 'Email', role: 'Role', manager: 'Manager', employee: 'Employee', company: 'Company', hourlyRate: 'Hourly rate', personalDetails: 'Personal details', personalDetailsCopy: 'Keep your contact information up to date.', firstName: 'First name', lastName: 'Last name', phone: 'Phone', firstNameRequired: 'First name is required.', profileUpdated: 'Profile updated successfully.', saving: 'Saving…', saveProfile: 'Save profile', changePassword: 'Change password', passwordCopy: 'Use at least 8 characters. Other signed-in sessions are revoked after a password change.', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', passwordsDoNotMatch: 'New passwords do not match.', passwordUpdated: 'Password updated successfully.', updating: 'Updating…', updatePassword: 'Update password', accountSecurity: 'Account & security', accountSecurityCopy: 'Sign out on this device or permanently remove your WorkTrack account.', signingOut: 'Signing out…', signOut: 'Sign out', deleteAccount: 'Delete account', deleteAccountCopy: 'This signs you out everywhere and disables access to your account. This action cannot be undone from the app.', typeDelete: 'Type DELETE to confirm', deleting: 'Deleting…'
    },
    dashboard: {
      myWorkspace: 'My workspace', companyWorkspace: 'Company workspace', goodMorning: 'Good morning', goodAfternoon: 'Good afternoon', goodEvening: 'Good evening', managerIntro: 'Here’s what’s happening at WorkTrack today.', employeeIntro: 'Your hours, approvals and salary in one place.', loading: 'Loading dashboard', employees: 'Employees', activeEmployees: 'Active employees', projects: 'Projects', activeProjects: 'Active projects', pendingApprovals: 'Pending approvals', weeksWaiting: 'Weeks waiting', payroll: 'Payroll', confirmedAmount: 'Confirmed amount', thisWeek: 'This week', allSavedEntries: 'All saved entries', pending: 'Pending', draftOrSubmitted: 'Draft or submitted', approved: 'Approved', confirmedHours: 'Confirmed hours', salary: 'Salary', predicted: 'predicted', needsAttention: 'Needs your attention', weekNeedsApproval: '{count} week needs approval', weeksNeedApproval: '{count} weeks need approval', reviewSubmittedHours: 'Review submitted hours before they become confirmed payroll.', reviewApprovals: 'Review approvals', confirmedSalary: 'Confirmed salary', predictedFromPending: '{amount} predicted from pending hours.', viewPayroll: 'View payroll', workspaceSummary: 'Workspace summary', quickActions: 'Quick actions', managerQuickCopy: 'Jump to the areas you use most.', employeeQuickCopy: 'Manage and review your work time.', manageTeam: 'Manage team', viewWorksites: 'View worksites', payrollReport: 'Payroll report', salaryOverview: 'Salary overview', myHours: 'My hours', addEditEntries: 'Add or edit entries', calendar: 'Calendar', monthlyOverview: 'Monthly hours overview', pendingCount: '{count} pending', teamThisWeek: 'Team this week', teamSummary: '{notSubmitted} not submitted · {needsChanges} need changes', notSubmitted: 'Not submitted', everyoneSubmitted: 'Everyone has submitted.', needsChanges: 'Needs changes', noRejectedWeeks: 'No rejected weeks.', waitingReview: 'Waiting review', nothingWaiting: 'Nothing waiting for review.', approvedWeeks: 'Approved', noApprovedWeeks: 'No approved weeks yet.'
    },
    calendar: { eyebrow: 'Work history', title: 'Calendar', intro: 'See your hours, projects and approval status by day.', navigation: 'Calendar navigation', previousMonth: 'Previous month', nextMonth: 'Next month', monthSummary: 'Month summary', loading: 'Loading calendar', statusLegend: 'Status legend', noHours: 'No hours recorded for this day.', workEntry: 'Work entry', addEntry: '+ Add entry', openHours: 'Open My Hours', overtimeSuffix: 'overtime' },
    approvals: { eyebrow: 'Manager workspace', title: 'Approvals', intro: 'Review submitted work weeks and confirm payroll-ready hours.', pendingSummary: 'Pending approval summary', pendingWeeks: 'Pending weeks', hoursWaiting: 'Hours waiting', loading: 'Loading approvals', allCaughtUp: "You're all caught up", noPending: 'There are no submitted weeks waiting for review.', pending: 'Pending', selectWeek: 'Select a week to review its entries.', pendingSubmissions: 'Pending submissions', submittedStatus: 'Submitted', loadingDetails: 'Loading details', totalHours: 'Total hours', workEntries: 'Work entries', decision: 'Decision', decisionCopy: 'Approve the week, or leave a clear note explaining what needs to change.', rejectionReason: 'Reason for rejection', optionalUntilRejecting: 'optional until rejecting', rejectionPlaceholder: "Example: Please correct Friday's project and resubmit.", rejectWithNote: 'Reject with note', approveWeek: 'Approve week', reasonRequired: 'Add a reason before rejecting this week.', employeeFallback: 'Employee' }
  },
  cs: {
    common: { failed: 'Nepodařilo se načíst.', failedToLoad: 'Stránku se nepodařilo otevřít. Zkuste to znovu.', backToHome: 'Zpět domů', loading: 'Načítání…', today: 'Dnes', previous: 'Předchozí', next: 'Další', totalHours: 'Celkem hodin', approved: 'Schváleno', submitted: 'Odesláno', draft: 'Koncept', rejected: 'Zamítnuto', overtime: 'Přesčas', project: 'Projekt', entries: 'záznamů' },
    app: { dashboard: 'Přehled', hours: 'Hodiny', employees: 'Zaměstnanci', approvals: 'Schvalování', profile: 'Profil' },
    auth: { email: 'E-mail', password: 'Heslo', login: 'Přihlásit se', loginTitle: 'Přihlášení', loginFailed: 'Přihlášení se nezdařilo. Zkontrolujte e-mail a heslo.', loggingIn: 'Přihlašování...', showPassword: 'Zobrazit heslo', hidePassword: 'Skrýt heslo', sessionState: 'Relace', sessionExpired: 'Relace vypršela', sessionExpiredSignIn: 'Pro pokračování se přihlaste znovu.', connectionLostKeepSession: 'Spojení bylo ztraceno. Relace zůstává uložená, zkuste to znovu.', sessionCheckFailedKeepSession: 'Kontrola relace se nezdařila. Zkuste to znovu.', goToSignIn: 'Přejít k přihlášení' },
    bottomTabs: { navLabel: 'Hlavní navigace' },
    guest: { titleLogin: 'Evidence pracovní doby', textLogin: 'Hodiny, schvalování a mzdy v jednom pracovním prostoru.', signInHeading: 'Přihlaste se a pokračujte', signInCopy: 'Použijte e-mail a heslo pro návrat do svého prostoru.' },
    settings: { languageCard: { title: 'Jazyk', label: 'Jazyk rozhraní', description: 'Vyberte jazyk WorkTrack. Volba se uloží na tomto zařízení.', uk: 'Українська', en: 'English', cs: 'Čeština' } },
    profile: {
      title: 'Profil', changeTemporaryPassword: 'Změňte dočasné heslo', temporaryPasswordCopy: 'Váš manažer vytvořil tento účet s dočasným heslem. Nastavte si vlastní heslo.', email: 'E-mail', role: 'Role', manager: 'Manažer', employee: 'Zaměstnanec', company: 'Společnost', hourlyRate: 'Hodinová sazba', personalDetails: 'Osobní údaje', personalDetailsCopy: 'Udržujte své kontaktní údaje aktuální.', firstName: 'Jméno', lastName: 'Příjmení', phone: 'Telefon', firstNameRequired: 'Jméno je povinné.', profileUpdated: 'Profil byl úspěšně aktualizován.', saving: 'Ukládání…', saveProfile: 'Uložit profil', changePassword: 'Změnit heslo', passwordCopy: 'Použijte alespoň 8 znaků. Po změně hesla budou ostatní přihlášené relace ukončeny.', currentPassword: 'Současné heslo', newPassword: 'Nové heslo', confirmPassword: 'Potvrďte nové heslo', passwordsDoNotMatch: 'Nová hesla se neshodují.', passwordUpdated: 'Heslo bylo úspěšně aktualizováno.', updating: 'Aktualizace…', updatePassword: 'Aktualizovat heslo', accountSecurity: 'Účet a zabezpečení', accountSecurityCopy: 'Odhlaste se na tomto zařízení nebo trvale odstraňte svůj účet WorkTrack.', signingOut: 'Odhlašování…', signOut: 'Odhlásit se', deleteAccount: 'Odstranit účet', deleteAccountCopy: 'Tímto se odhlásíte na všech zařízeních a zrušíte přístup k účtu. Tuto akci nelze v aplikaci vrátit zpět.', typeDelete: 'Pro potvrzení napište DELETE', deleting: 'Odstraňování…'
    },
    dashboard: {
      myWorkspace: 'Můj pracovní prostor', companyWorkspace: 'Pracovní prostor firmy', goodMorning: 'Dobré ráno', goodAfternoon: 'Dobré odpoledne', goodEvening: 'Dobrý večer', managerIntro: 'Podívejte se, co se dnes ve WorkTrack děje.', employeeIntro: 'Vaše hodiny, schvalování a mzda na jednom místě.', loading: 'Načítání přehledu', employees: 'Zaměstnanci', activeEmployees: 'Aktivní zaměstnanci', projects: 'Projekty', activeProjects: 'Aktivní projekty', pendingApprovals: 'Čeká na schválení', weeksWaiting: 'Čekající týdny', payroll: 'Mzdy', confirmedAmount: 'Potvrzená částka', thisWeek: 'Tento týden', allSavedEntries: 'Všechny uložené záznamy', pending: 'Čeká', draftOrSubmitted: 'Koncept nebo odesláno', approved: 'Schváleno', confirmedHours: 'Potvrzené hodiny', salary: 'Mzda', predicted: 'předpoklad', needsAttention: 'Vyžaduje vaši pozornost', weekNeedsApproval: '{count} týden čeká na schválení', weeksNeedApproval: '{count} týdnů čeká na schválení', reviewSubmittedHours: 'Zkontrolujte odeslané hodiny před potvrzením mzdy.', reviewApprovals: 'Zkontrolovat schválení', confirmedSalary: 'Potvrzená mzda', predictedFromPending: '{amount} předpokládaná mzda z čekajících hodin.', viewPayroll: 'Zobrazit mzdy', workspaceSummary: 'Souhrn pracovního prostoru', quickActions: 'Rychlé akce', managerQuickCopy: 'Přejděte do nejčastěji používaných částí.', employeeQuickCopy: 'Spravujte a kontrolujte svou pracovní dobu.', manageTeam: 'Spravovat tým', viewWorksites: 'Zobrazit pracoviště', payrollReport: 'Mzdový přehled', salaryOverview: 'Přehled mzdy', myHours: 'Moje hodiny', addEditEntries: 'Přidat nebo upravit záznamy', calendar: 'Kalendář', monthlyOverview: 'Měsíční přehled hodin', pendingCount: '{count} čeká', teamThisWeek: 'Tým tento týden', teamSummary: '{notSubmitted} neodesláno · {needsChanges} vyžaduje změny', notSubmitted: 'Neodesláno', everyoneSubmitted: 'Všichni už odeslali.', needsChanges: 'Vyžaduje změny', noRejectedWeeks: 'Žádné zamítnuté týdny.', waitingReview: 'Čeká na kontrolu', nothingWaiting: 'Nic nečeká na kontrolu.', approvedWeeks: 'Schváleno', noApprovedWeeks: 'Zatím žádné schválené týdny.'
    },
    calendar: { eyebrow: 'Historie práce', title: 'Kalendář', intro: 'Prohlížejte si hodiny, projekty a stav schválení podle jednotlivých dnů.', navigation: 'Navigace kalendáře', previousMonth: 'Předchozí měsíc', nextMonth: 'Další měsíc', monthSummary: 'Souhrn měsíce', loading: 'Načítání kalendáře', statusLegend: 'Legenda stavů', noHours: 'Pro tento den nejsou zaznamenané žádné hodiny.', workEntry: 'Pracovní záznam', addEntry: '+ Přidat záznam', openHours: 'Otevřít Moje hodiny', overtimeSuffix: 'přesčas' },
    approvals: { eyebrow: 'Prostor manažera', title: 'Schvalování', intro: 'Kontrolujte odeslané pracovní týdny a potvrzujte hodiny připravené pro mzdy.', pendingSummary: 'Souhrn čekajících schválení', pendingWeeks: 'Čekající týdny', hoursWaiting: 'Čekající hodiny', loading: 'Načítání schválení', allCaughtUp: 'Vše je zkontrolováno', noPending: 'Žádné odeslané týdny nečekají na kontrolu.', pending: 'Čeká', selectWeek: 'Vyberte týden a zkontrolujte jeho záznamy.', pendingSubmissions: 'Čekající odeslání', submittedStatus: 'Odesláno', loadingDetails: 'Načítání detailů', totalHours: 'Celkem hodin', workEntries: 'Pracovní záznamy', decision: 'Rozhodnutí', decisionCopy: 'Schvalte týden, nebo přidejte jasnou poznámku s tím, co je potřeba upravit.', rejectionReason: 'Důvod zamítnutí', optionalUntilRejecting: 'do zamítnutí nepovinné', rejectionPlaceholder: 'Například: Opravte prosím projekt u pátku a odešlete týden znovu.', rejectWithNote: 'Zamítnout s poznámkou', approveWeek: 'Schválit týden', reasonRequired: 'Před zamítnutím tohoto týdne přidejte důvod.', employeeFallback: 'Zaměstnanec' }
  },
};

export function getMessage(language, key) {
  const parts = String(key || '').split('.');
  let current = messages[language] || messages.uk;
  for (const part of parts) {
    if (!current || typeof current !== 'object') return key;
    current = current[part];
  }
  return typeof current === 'string' ? current : key;
}
