export const messages = {
  uk: {
    common: { failed: 'Не вдалося завантажити.', backToHome: 'Повернутися на головну' },
    app: { dashboard: 'Дашборд', hours: 'Години', employees: 'Працівники', approvals: 'Погодження', profile: 'Профіль' },
    auth: { email: 'E-mail', password: 'Пароль', login: 'Увійти', loginTitle: 'Вхід', loginFailed: 'Не вдалося увійти. Перевірте email і пароль.', loggingIn: 'Вхід...', showPassword: 'Показати пароль', hidePassword: 'Приховати пароль', sessionState: 'Сесія', sessionExpired: 'Сесію завершено', sessionExpiredSignIn: 'Увійдіть ще раз, щоб продовжити роботу.', connectionLostKeepSession: 'З’єднання втрачено. Сесію збережено, спробуйте ще раз.', sessionCheckFailedKeepSession: 'Не вдалося перевірити сесію. Спробуйте ще раз.', goToSignIn: 'Перейти до входу' },
    bottomTabs: { navLabel: 'Основна навігація' },
    guest: { titleLogin: 'Облік робочого часу', textLogin: 'Години, погодження та оплата в одному робочому просторі.', signInHeading: 'Увійдіть, щоб продовжити', signInCopy: 'Використовуйте email і пароль, щоб повернутися до свого простору.' },
    settings: { languageCard: { title: 'Мова', label: 'Мова інтерфейсу', description: 'Виберіть мову WorkTrack. Налаштування збережеться на цьому пристрої.', uk: 'Українська', en: 'English', cs: 'Čeština' } },
    profile: {
      title: 'Профіль', changeTemporaryPassword: 'Змініть тимчасовий пароль', temporaryPasswordCopy: 'Менеджер створив цей акаунт із тимчасовим паролем. Встановіть власний пароль.', email: 'E-mail', role: 'Роль', manager: 'Менеджер', employee: 'Працівник', company: 'Компанія', hourlyRate: 'Погодинна ставка', personalDetails: 'Особисті дані', personalDetailsCopy: 'Підтримуйте контактні дані в актуальному стані.', firstName: 'Ім’я', lastName: 'Прізвище', phone: 'Телефон', firstNameRequired: 'Ім’я є обов’язковим.', profileUpdated: 'Профіль успішно оновлено.', saving: 'Збереження…', saveProfile: 'Зберегти профіль', changePassword: 'Змінити пароль', passwordCopy: 'Використовуйте щонайменше 8 символів. Після зміни пароля інші активні сесії буде завершено.', currentPassword: 'Поточний пароль', newPassword: 'Новий пароль', confirmPassword: 'Підтвердіть новий пароль', passwordsDoNotMatch: 'Нові паролі не збігаються.', passwordUpdated: 'Пароль успішно оновлено.', updating: 'Оновлення…', updatePassword: 'Оновити пароль', accountSecurity: 'Акаунт і безпека', accountSecurityCopy: 'Вийдіть на цьому пристрої або назавжди видаліть свій акаунт WorkTrack.', signingOut: 'Вихід…', signOut: 'Вийти', deleteAccount: 'Видалити акаунт', deleteAccountCopy: 'Це завершить усі сесії та вимкне доступ до акаунта. Дію неможливо скасувати в застосунку.', typeDelete: 'Введіть DELETE для підтвердження', deleting: 'Видалення…'
    },
    dashboard: {
      myWorkspace: 'Мій робочий простір', companyWorkspace: 'Робочий простір компанії', goodMorning: 'Доброго ранку', goodAfternoon: 'Добрий день', goodEvening: 'Добрий вечір', managerIntro: 'Ось що відбувається у WorkTrack сьогодні.', employeeIntro: 'Ваші години, погодження та зарплата в одному місці.', loading: 'Завантаження дашборду', employees: 'Працівники', activeEmployees: 'Активні працівники', projects: 'Проєкти', activeProjects: 'Активні проєкти', pendingApprovals: 'Очікують погодження', weeksWaiting: 'Тижні в очікуванні', payroll: 'Зарплата', confirmedAmount: 'Підтверджена сума', thisWeek: 'Цього тижня', allSavedEntries: 'Усі збережені записи', pending: 'В очікуванні', draftOrSubmitted: 'Чернетки або відправлені', approved: 'Підтверджено', confirmedHours: 'Підтверджені години', salary: 'Зарплата', predicted: 'очікувано', needsAttention: 'Потребує вашої уваги', weekNeedsApproval: '{count} тиждень потребує погодження', weeksNeedApproval: '{count} тижнів потребують погодження', reviewSubmittedHours: 'Перевірте відправлені години до нарахування зарплати.', reviewApprovals: 'Перевірити погодження', confirmedSalary: 'Підтверджена зарплата', predictedFromPending: '{amount} очікується з непідтверджених годин.', viewPayroll: 'Переглянути зарплату', workspaceSummary: 'Огляд робочого простору', quickActions: 'Швидкі дії', managerQuickCopy: 'Перейдіть до розділів, якими користуєтесь найчастіше.', employeeQuickCopy: 'Керуйте та перевіряйте свій робочий час.', manageTeam: 'Керувати командою', viewWorksites: 'Переглянути об’єкти', payrollReport: 'Звіт по зарплаті', salaryOverview: 'Огляд зарплати', myHours: 'Мої години', addEditEntries: 'Додати або змінити записи', calendar: 'Календар', monthlyOverview: 'Огляд годин за місяць', pendingCount: '{count} в очікуванні', teamThisWeek: 'Команда цього тижня', teamSummary: '{notSubmitted} не відправили · {needsChanges} потребують змін', notSubmitted: 'Не відправлено', everyoneSubmitted: 'Усі вже відправили.', needsChanges: 'Потрібні зміни', noRejectedWeeks: 'Немає відхилених тижнів.', waitingReview: 'Очікують перевірки', nothingWaiting: 'Нічого не очікує перевірки.', approvedWeeks: 'Погоджено', noApprovedWeeks: 'Ще немає погоджених тижнів.'
    }
  },
  en: {
    common: { failed: 'Failed to load.', backToHome: 'Back to home' },
    app: { dashboard: 'Dashboard', hours: 'Hours', employees: 'Employees', approvals: 'Approvals', profile: 'Profile' },
    auth: { email: 'Email', password: 'Password', login: 'Sign in', loginTitle: 'Sign in', loginFailed: 'Sign-in failed. Check your email and password.', loggingIn: 'Signing in...', showPassword: 'Show password', hidePassword: 'Hide password', sessionState: 'Session', sessionExpired: 'Session expired', sessionExpiredSignIn: 'Sign in again to continue working.', connectionLostKeepSession: 'Connection was lost. Your session is kept, try again.', sessionCheckFailedKeepSession: 'Session check failed. Try again.', goToSignIn: 'Go to sign in' },
    bottomTabs: { navLabel: 'Primary navigation' },
    guest: { titleLogin: 'Work hours tracking', textLogin: 'Hours, approvals, and payroll in one workspace.', signInHeading: 'Sign in to continue', signInCopy: 'Use your email and password to return to your workspace.' },
    settings: { languageCard: { title: 'Language', label: 'Interface language', description: 'Choose the WorkTrack language. Your choice is saved on this device.', uk: 'Українська', en: 'English', cs: 'Čeština' } },
    profile: {
      title: 'Profile', changeTemporaryPassword: 'Change your temporary password', temporaryPasswordCopy: 'Your manager created this account with a temporary password. Set your own password now.', email: 'Email', role: 'Role', manager: 'Manager', employee: 'Employee', company: 'Company', hourlyRate: 'Hourly rate', personalDetails: 'Personal details', personalDetailsCopy: 'Keep your contact information up to date.', firstName: 'First name', lastName: 'Last name', phone: 'Phone', firstNameRequired: 'First name is required.', profileUpdated: 'Profile updated successfully.', saving: 'Saving…', saveProfile: 'Save profile', changePassword: 'Change password', passwordCopy: 'Use at least 8 characters. Other signed-in sessions are revoked after a password change.', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', passwordsDoNotMatch: 'New passwords do not match.', passwordUpdated: 'Password updated successfully.', updating: 'Updating…', updatePassword: 'Update password', accountSecurity: 'Account & security', accountSecurityCopy: 'Sign out on this device or permanently remove your WorkTrack account.', signingOut: 'Signing out…', signOut: 'Sign out', deleteAccount: 'Delete account', deleteAccountCopy: 'This signs you out everywhere and disables access to your account. This action cannot be undone from the app.', typeDelete: 'Type DELETE to confirm', deleting: 'Deleting…'
    },
    dashboard: {
      myWorkspace: 'My workspace', companyWorkspace: 'Company workspace', goodMorning: 'Good morning', goodAfternoon: 'Good afternoon', goodEvening: 'Good evening', managerIntro: 'Here’s what’s happening at WorkTrack today.', employeeIntro: 'Your hours, approvals and salary in one place.', loading: 'Loading dashboard', employees: 'Employees', activeEmployees: 'Active employees', projects: 'Projects', activeProjects: 'Active projects', pendingApprovals: 'Pending approvals', weeksWaiting: 'Weeks waiting', payroll: 'Payroll', confirmedAmount: 'Confirmed amount', thisWeek: 'This week', allSavedEntries: 'All saved entries', pending: 'Pending', draftOrSubmitted: 'Draft or submitted', approved: 'Approved', confirmedHours: 'Confirmed hours', salary: 'Salary', predicted: 'predicted', needsAttention: 'Needs your attention', weekNeedsApproval: '{count} week needs approval', weeksNeedApproval: '{count} weeks need approval', reviewSubmittedHours: 'Review submitted hours before they become confirmed payroll.', reviewApprovals: 'Review approvals', confirmedSalary: 'Confirmed salary', predictedFromPending: '{amount} predicted from pending hours.', viewPayroll: 'View payroll', workspaceSummary: 'Workspace summary', quickActions: 'Quick actions', managerQuickCopy: 'Jump to the areas you use most.', employeeQuickCopy: 'Manage and review your work time.', manageTeam: 'Manage team', viewWorksites: 'View worksites', payrollReport: 'Payroll report', salaryOverview: 'Salary overview', myHours: 'My hours', addEditEntries: 'Add or edit entries', calendar: 'Calendar', monthlyOverview: 'Monthly hours overview', pendingCount: '{count} pending', teamThisWeek: 'Team this week', teamSummary: '{notSubmitted} not submitted · {needsChanges} need changes', notSubmitted: 'Not submitted', everyoneSubmitted: 'Everyone has submitted.', needsChanges: 'Needs changes', noRejectedWeeks: 'No rejected weeks.', waitingReview: 'Waiting review', nothingWaiting: 'Nothing waiting for review.', approvedWeeks: 'Approved', noApprovedWeeks: 'No approved weeks yet.'
    }
  },
  cs: {
    common: { failed: 'Nepodařilo se načíst.', backToHome: 'Zpět domů' },
    app: { dashboard: 'Přehled', hours: 'Hodiny', employees: 'Zaměstnanci', approvals: 'Schvalování', profile: 'Profil' },
    auth: { email: 'E-mail', password: 'Heslo', login: 'Přihlásit se', loginTitle: 'Přihlášení', loginFailed: 'Přihlášení se nezdařilo. Zkontrolujte e-mail a heslo.', loggingIn: 'Přihlašování...', showPassword: 'Zobrazit heslo', hidePassword: 'Skrýt heslo', sessionState: 'Relace', sessionExpired: 'Relace vypršela', sessionExpiredSignIn: 'Pro pokračování se přihlaste znovu.', connectionLostKeepSession: 'Spojení bylo ztraceno. Relace zůstává uložená, zkuste to znovu.', sessionCheckFailedKeepSession: 'Kontrola relace se nezdařila. Zkuste to znovu.', goToSignIn: 'Přejít k přihlášení' },
    bottomTabs: { navLabel: 'Hlavní navigace' },
    guest: { titleLogin: 'Evidence pracovní doby', textLogin: 'Hodiny, schvalování a mzdy v jednom pracovním prostoru.', signInHeading: 'Přihlaste se a pokračujte', signInCopy: 'Použijte e-mail a heslo pro návrat do svého prostoru.' },
    settings: { languageCard: { title: 'Jazyk', label: 'Jazyk rozhraní', description: 'Vyberte jazyk WorkTrack. Volba se uloží na tomto zařízení.', uk: 'Українська', en: 'English', cs: 'Čeština' } },
    profile: {
      title: 'Profil', changeTemporaryPassword: 'Změňte dočasné heslo', temporaryPasswordCopy: 'Váš manažer vytvořil tento účet s dočasným heslem. Nastavte si vlastní heslo.', email: 'E-mail', role: 'Role', manager: 'Manažer', employee: 'Zaměstnanec', company: 'Společnost', hourlyRate: 'Hodinová sazba', personalDetails: 'Osobní údaje', personalDetailsCopy: 'Udržujte své kontaktní údaje aktuální.', firstName: 'Jméno', lastName: 'Příjmení', phone: 'Telefon', firstNameRequired: 'Jméno je povinné.', profileUpdated: 'Profil byl úspěšně aktualizován.', saving: 'Ukládání…', saveProfile: 'Uložit profil', changePassword: 'Změnit heslo', passwordCopy: 'Použijte alespoň 8 znaků. Po změně hesla budou ostatní přihlášené relace ukončeny.', currentPassword: 'Současné heslo', newPassword: 'Nové heslo', confirmPassword: 'Potvrďte nové heslo', passwordsDoNotMatch: 'Nová hesla se neshodují.', passwordUpdated: 'Heslo bylo úspěšně změněno.', updating: 'Aktualizace…', updatePassword: 'Aktualizovat heslo', accountSecurity: 'Účet a zabezpečení', accountSecurityCopy: 'Odhlaste se na tomto zařízení nebo trvale odstraňte svůj účet WorkTrack.', signingOut: 'Odhlašování…', signOut: 'Odhlásit se', deleteAccount: 'Odstranit účet', deleteAccountCopy: 'Tímto se odhlásíte ze všech zařízení a přístup k účtu bude deaktivován. Tuto akci nelze v aplikaci vrátit zpět.', typeDelete: 'Pro potvrzení napište DELETE', deleting: 'Odstraňování…'
    },
    dashboard: {
      myWorkspace: 'Můj pracovní prostor', companyWorkspace: 'Pracovní prostor firmy', goodMorning: 'Dobré ráno', goodAfternoon: 'Dobrý den', goodEvening: 'Dobrý večer', managerIntro: 'Tady je přehled toho, co se dnes ve WorkTrack děje.', employeeIntro: 'Vaše hodiny, schválení a mzda na jednom místě.', loading: 'Načítání přehledu', employees: 'Zaměstnanci', activeEmployees: 'Aktivní zaměstnanci', projects: 'Projekty', activeProjects: 'Aktivní projekty', pendingApprovals: 'Čeká na schválení', weeksWaiting: 'Čekající týdny', payroll: 'Mzdy', confirmedAmount: 'Schválená částka', thisWeek: 'Tento týden', allSavedEntries: 'Všechny uložené záznamy', pending: 'Čeká', draftOrSubmitted: 'Koncept nebo odesláno', approved: 'Schváleno', confirmedHours: 'Schválené hodiny', salary: 'Mzda', predicted: 'odhad', needsAttention: 'Vyžaduje vaši pozornost', weekNeedsApproval: '{count} týden čeká na schválení', weeksNeedApproval: '{count} týdnů čeká na schválení', reviewSubmittedHours: 'Zkontrolujte odeslané hodiny před jejich započtením do mzdy.', reviewApprovals: 'Zkontrolovat schválení', confirmedSalary: 'Schválená mzda', predictedFromPending: '{amount} odhad z čekajících hodin.', viewPayroll: 'Zobrazit mzdu', workspaceSummary: 'Souhrn pracovního prostoru', quickActions: 'Rychlé akce', managerQuickCopy: 'Přejděte rychle do nejčastěji používaných částí.', employeeQuickCopy: 'Spravujte a kontrolujte svou pracovní dobu.', manageTeam: 'Spravovat tým', viewWorksites: 'Zobrazit pracoviště', payrollReport: 'Mzdový přehled', salaryOverview: 'Přehled mzdy', myHours: 'Moje hodiny', addEditEntries: 'Přidat nebo upravit záznamy', calendar: 'Kalendář', monthlyOverview: 'Měsíční přehled hodin', pendingCount: '{count} čeká', teamThisWeek: 'Tým tento týden', teamSummary: '{notSubmitted} neodesláno · {needsChanges} vyžaduje změny', notSubmitted: 'Neodesláno', everyoneSubmitted: 'Všichni už odeslali.', needsChanges: 'Vyžaduje změny', noRejectedWeeks: 'Žádné zamítnuté týdny.', waitingReview: 'Čeká na kontrolu', nothingWaiting: 'Nic nečeká na kontrolu.', approvedWeeks: 'Schváleno', noApprovedWeeks: 'Zatím žádné schválené týdny.'
    }
  },
};

export function getMessage(language, key) {
  const parts = String(key || '').split('.');
  let current = messages[language] || messages.uk;
  for (const part of parts) {
    if (!current || typeof current !== 'object') return key;
    current = current[part];
  }
  return typeof current === 'string' ? current : key;
}
