export const teamMessages = {
  uk: {
    employees: { employee:'Працівник',team:'Команда',title:'Працівники',active:'активних',total:'всього',addEmployee:'Додати працівника',addCopy:'Працівник повинен змінити тимчасовий пароль після першого входу.',firstName:'Ім’я',lastName:'Прізвище',email:'E-mail',temporaryPassword:'Тимчасовий пароль',hourlyRate:'Погодинна ставка CZK',employeeAdded:'Працівника додано.',rateUpdated:'Погодинну ставку оновлено.',reactivated:'Працівника знову активовано.',deactivated:'Працівника деактивовано.',passwordMin:'Тимчасовий пароль має містити щонайменше 8 символів.',passwordReset:'Пароль скинуто для {name}.',list:'Список працівників',currentWeek:'Поточний тиждень',loading:'Завантаження працівників',none:'Працівників ще немає',week:'тиждень',pending:'очікує',status:'статус',rate:'Ставка CZK',saveRate:'Зберегти ставку',deactivate:'Деактивувати',reactivate:'Активувати',resetPassword:'Скинути пароль',newTemporaryPassword:'Новий тимчасовий пароль',minPlaceholder:'Щонайменше 8 символів',resetCopy:'Активні сесії буде завершено. Працівник повинен змінити цей пароль після входу.',setTemporaryPassword:'Встановити тимчасовий пароль',activeStatus:'Активний',inactiveStatus:'Неактивний',manage:'Керувати',close:'Закрити',employeeDetails:'Дані працівника',actions:'Дії',cancel:'Скасувати' }
  },
  cs: {
    employees: { employee:'Zaměstnanec',team:'Tým',title:'Zaměstnanci',active:'aktivních',total:'celkem',addEmployee:'Přidat zaměstnance',addCopy:'Zaměstnanec musí po prvním přihlášení změnit dočasné heslo.',firstName:'Jméno',lastName:'Příjmení',email:'E-mail',temporaryPassword:'Dočasné heslo',hourlyRate:'Hodinová sazba CZK',employeeAdded:'Zaměstnanec byl přidán.',rateUpdated:'Hodinová sazba byla aktualizována.',reactivated:'Zaměstnanec byl znovu aktivován.',deactivated:'Zaměstnanec byl deaktivován.',passwordMin:'Dočasné heslo musí mít alespoň 8 znaků.',passwordReset:'Heslo pro {name} bylo resetováno.',list:'Seznam zaměstnanců',currentWeek:'Aktuální týden',loading:'Načítání zaměstnanců',none:'Zatím žádní zaměstnanci',week:'týden',pending:'čeká',status:'stav',rate:'Sazba CZK',saveRate:'Uložit sazbu',deactivate:'Deaktivovat',reactivate:'Aktivovat',resetPassword:'Resetovat heslo',newTemporaryPassword:'Nové dočasné heslo',minPlaceholder:'Alespoň 8 znaků',resetCopy:'Aktivní relace budou ukončeny. Zaměstnanec musí toto heslo po přihlášení změnit.',setTemporaryPassword:'Nastavit dočasné heslo',activeStatus:'Aktivní',inactiveStatus:'Neaktivní',manage:'Spravovat',close:'Zavřít',employeeDetails:'Údaje zaměstnance',actions:'Akce',cancel:'Zrušit' }
  },
  en: {
    employees: { employee:'Employee',team:'Team',title:'Employees',active:'active',total:'total',addEmployee:'Add employee',addCopy:'The employee must replace the temporary password after the first sign in.',firstName:'First name',lastName:'Last name',email:'Email',temporaryPassword:'Temporary password',hourlyRate:'Hourly rate CZK',employeeAdded:'Employee added.',rateUpdated:'Hourly rate updated.',reactivated:'Employee reactivated.',deactivated:'Employee deactivated.',passwordMin:'Temporary password must be at least 8 characters long.',passwordReset:'Password reset for {name}.',list:'Employee list',currentWeek:'Current week',loading:'Loading employees',none:'No employees yet',week:'week',pending:'pending',status:'status',rate:'Rate CZK',saveRate:'Save rate',deactivate:'Deactivate',reactivate:'Reactivate',resetPassword:'Reset password',newTemporaryPassword:'New temporary password',minPlaceholder:'At least 8 characters',resetCopy:'Existing sessions will be signed out. The employee must change this password after signing in.',setTemporaryPassword:'Set temporary password',activeStatus:'Active',inactiveStatus:'Inactive',manage:'Manage',close:'Close',employeeDetails:'Employee details',actions:'Actions',cancel:'Cancel' }
  }
};
