export const worktrackMessages = {
  uk: {
    projects: { eyebrow: 'Об’єкти', title: 'Проєкти', loadError: 'Не вдалося завантажити проєкти', activeTotal: '{active} активних · {total} всього', edit: 'Редагувати проєкт', new: 'Новий проєкт', copy: 'Проєкти прив’язують години працівників до поточної компанії.', name: 'Назва', address: 'Адреса', description: 'Опис', cancel: 'Скасувати', save: 'Зберегти проєкт', create: 'Створити проєкт', list: 'Список проєктів', listCopy: 'Неактивні проєкти залишаються в історії та можуть бути активовані знову.', loading: 'Завантаження проєктів', empty: 'Проєктів ще немає', noDetails: 'Немає деталей', active: 'Активний', inactive: 'Неактивний', editAction: 'Редагувати', deactivate: 'Деактивувати', reactivate: 'Активувати' },
    payroll: { title: 'Звіт по зарплаті', printCopy: 'Використайте друк у браузері та виберіть «Зберегти як PDF».', back: 'Назад до дашборду', print: 'Друк / Зберегти PDF', week: 'Тиждень', month: 'Місяць', previous: '← Попередній', next: 'Наступний →', today: 'Сьогодні', periodDate: 'Дата періоду', preparing: 'Підготовка звіту', companyReport: 'Звіт по зарплаті компанії', employeeStatement: 'Розрахунок зарплати працівника', managerReport: 'Звіт менеджера', weekStart: 'Початок тижня', weekEnd: 'Кінець тижня', weekStatus: 'Статус тижня', hourlyRate: 'Погодинна ставка', periodType: 'Тип періоду', period: 'Період', employees: 'Працівники', employeesWithHours: 'Працівники з годинами', payrollTotals: 'Підсумки зарплати', hoursSalary: 'Години та зарплата', approvedHours: 'Підтверджені години', pendingHours: 'Години в очікуванні', confirmedPayroll: 'Підтверджена зарплата', predictedPayroll: 'Очікувана зарплата', totalSavedHours: 'Усі збережені години', confirmedSalary: 'Підтверджена зарплата', predictedSalary: 'Очікувана зарплата', breakdown: 'По працівниках', employee: 'Працівник', status: 'Статус', rate: 'Ставка', approved: 'Підтверджено', pending: 'В очікуванні', confirmed: 'Підтверджено', predicted: 'Очікувано', footer: 'Підтверджені суми розраховуються з погоджених робочих записів. Очікувані суми враховують чернетки та відправлені записи й можуть змінитися після перевірки менеджером. Відхилені години не входять у зарплату, доки їх не виправлено та не відправлено повторно.', generated: 'Створено у WorkTrack' },
    company: { eyebrow: 'Компанія', title: 'Налаштування', loadError: 'Не вдалося завантажити компанію', current: 'Поточна компанія', identity: 'Ідентифікація робочого простору', copy: 'Ця назва відображається менеджерам і працівникам у WorkTrack.', loading: 'Завантаження компанії', name: 'Назва компанії', nameRequired: 'Назва компанії обов’язкова.', savedMessage: 'Назву компанії збережено.', slug: 'Slug робочого простору', slugCopy: 'Slug — це стабільний внутрішній ідентифікатор, який не змінюється при перейменуванні компанії.', saving: 'Збереження…', saveChanges: 'Зберегти зміни', saved: 'Збережено' },
    notifications: { eyebrow: 'Вхідні', title: 'Сповіщення', loadError: 'Не вдалося завантажити сповіщення', unread: '{count} непрочитаних', caughtUp: 'Усе переглянуто', markAll: 'Позначити все прочитаним', loading: 'Завантаження сповіщень', empty: 'Сповіщень ще немає', emptyCopy: 'Оновлення про відправлені та перевірені тижні з’являться тут.' }
  },
  en: {
    projects: { eyebrow: 'Worksites', title: 'Projects', loadError: 'Unable to load projects', activeTotal: '{active} active · {total} total', edit: 'Edit project', new: 'New project', copy: 'Projects keep employee hours scoped to the current company.', name: 'Name', address: 'Address', description: 'Description', cancel: 'Cancel', save: 'Save project', create: 'Create project', list: 'Project list', listCopy: 'Inactive projects stay available for history and can be reactivated.', loading: 'Loading projects', empty: 'No projects yet', noDetails: 'No details', active: 'Active', inactive: 'Inactive', editAction: 'Edit', deactivate: 'Deactivate', reactivate: 'Reactivate' },
    payroll: { title: 'Payroll report', printCopy: 'Use your browser print dialog and choose “Save as PDF”.', back: 'Back to dashboard', print: 'Print / Save PDF', week: 'Week', month: 'Month', previous: '← Previous', next: 'Next →', today: 'Today', periodDate: 'Period date', preparing: 'Preparing payroll report', companyReport: 'Company payroll report', employeeStatement: 'Employee payroll statement', managerReport: 'Manager report', weekStart: 'Week start', weekEnd: 'Week end', weekStatus: 'Week status', hourlyRate: 'Hourly rate', periodType: 'Period type', period: 'Period', employees: 'Employees', employeesWithHours: 'Employees with hours', payrollTotals: 'Payroll totals', hoursSalary: 'Hours and salary', approvedHours: 'Approved hours', pendingHours: 'Pending hours', confirmedPayroll: 'Confirmed payroll', predictedPayroll: 'Predicted payroll', totalSavedHours: 'Total saved hours', confirmedSalary: 'Confirmed salary', predictedSalary: 'Predicted salary', breakdown: 'Employee breakdown', employee: 'Employee', status: 'Status', rate: 'Rate', approved: 'Approved', pending: 'Pending', confirmed: 'Confirmed', predicted: 'Predicted', footer: 'Confirmed amounts are calculated from approved work entries. Predicted amounts use draft and submitted entries and may change after manager review. Rejected work is not included in payroll until it is corrected and resubmitted.', generated: 'Generated by WorkTrack' },
    company: { eyebrow: 'Company', title: 'Settings', loadError: 'Unable to load company', current: 'Current company', identity: 'Workspace identity', copy: 'This name is shown to managers and employees across WorkTrack.', loading: 'Loading company', name: 'Company name', nameRequired: 'Company name is required.', savedMessage: 'Company name saved.', slug: 'Workspace slug', slugCopy: 'The workspace slug is a stable internal identifier and is not changed when you rename the company.', saving: 'Saving…', saveChanges: 'Save changes', saved: 'Saved' },
    notifications: { eyebrow: 'Inbox', title: 'Notifications', loadError: 'Unable to load notifications', unread: '{count} unread', caughtUp: 'You are all caught up', markAll: 'Mark all read', loading: 'Loading notifications', empty: 'No notifications yet', emptyCopy: 'Updates about submitted and reviewed weeks will appear here.' }
  },
  cs: {
    projects: { eyebrow: 'Zakázky', title: 'Projekty', loadError: 'Projekty se nepodařilo načíst', activeTotal: '{active} aktivních · {total} celkem', edit: 'Upravit projekt', new: 'Nový projekt', copy: 'Projekty přiřazují odpracované hodiny zaměstnanců k aktuální společnosti.', name: 'Název', address: 'Adresa', description: 'Popis', cancel: 'Zrušit', save: 'Uložit projekt', create: 'Vytvořit projekt', list: 'Seznam projektů', listCopy: 'Neaktivní projekty zůstávají v historii a lze je znovu aktivovat.', loading: 'Načítání projektů', empty: 'Zatím nejsou žádné projekty', noDetails: 'Bez podrobností', active: 'Aktivní', inactive: 'Neaktivní', editAction: 'Upravit', deactivate: 'Deaktivovat', reactivate: 'Znovu aktivovat' },
    payroll: { title: 'Mzdový přehled', printCopy: 'Použijte tisk v prohlížeči a zvolte „Uložit jako PDF“.', back: 'Zpět na přehled', print: 'Tisk / Uložit PDF', week: 'Týden', month: 'Měsíc', previous: '← Předchozí', next: 'Další →', today: 'Dnes', periodDate: 'Datum období', preparing: 'Příprava mzdového přehledu', companyReport: 'Mzdový přehled společnosti', employeeStatement: 'Mzdový přehled zaměstnance', managerReport: 'Přehled manažera', weekStart: 'Začátek týdne', weekEnd: 'Konec týdne', weekStatus: 'Stav týdne', hourlyRate: 'Hodinová sazba', periodType: 'Typ období', period: 'Období', employees: 'Zaměstnanci', employeesWithHours: 'Zaměstnanci s hodinami', payrollTotals: 'Souhrn mezd', hoursSalary: 'Hodiny a mzda', approvedHours: 'Schválené hodiny', pendingHours: 'Čekající hodiny', confirmedPayroll: 'Potvrzené mzdy', predictedPayroll: 'Očekávané mzdy', totalSavedHours: 'Celkem uložených hodin', confirmedSalary: 'Potvrzená mzda', predictedSalary: 'Očekávaná mzda', breakdown: 'Přehled zaměstnanců', employee: 'Zaměstnanec', status: 'Stav', rate: 'Sazba', approved: 'Schváleno', pending: 'Čeká', confirmed: 'Potvrzeno', predicted: 'Očekáváno', footer: 'Potvrzené částky se počítají ze schválených pracovních záznamů. Očekávané částky zahrnují koncepty a odeslané záznamy a mohou se po kontrole manažerem změnit. Zamítnutá práce se do mzdy nezapočítá, dokud není opravena a znovu odeslána.', generated: 'Vygenerováno ve WorkTrack' },
    company: { eyebrow: 'Společnost', title: 'Nastavení', loadError: 'Společnost se nepodařilo načíst', current: 'Aktuální společnost', identity: 'Identita pracovního prostoru', copy: 'Tento název se zobrazuje manažerům i zaměstnancům ve WorkTrack.', loading: 'Načítání společnosti', name: 'Název společnosti', nameRequired: 'Název společnosti je povinný.', savedMessage: 'Název společnosti byl uložen.', slug: 'Slug pracovního prostoru', slugCopy: 'Slug je stabilní interní identifikátor a při přejmenování společnosti se nemění.', saving: 'Ukládání…', saveChanges: 'Uložit změny', saved: 'Uloženo' },
    notifications: { eyebrow: 'Doručené', title: 'Oznámení', loadError: 'Oznámení se nepodařilo načíst', unread: '{count} nepřečtených', caughtUp: 'Vše je vyřízeno', markAll: 'Označit vše jako přečtené', loading: 'Načítání oznámení', empty: 'Zatím žádná oznámení', emptyCopy: 'Aktualizace o odeslaných a zkontrolovaných týdnech se zobrazí zde.' }
  }
};

const locales = { uk: 'uk-UA', en: 'en-GB', cs: 'cs-CZ' };

export function getWorktrackMessage(language, key, values = {}) {
  const parts = String(key || '').split('.');
  let current = worktrackMessages[language] || worktrackMessages.uk;
  for (const part of parts) current = current?.[part];
  const template = typeof current === 'string' ? current : key;
  return template.replace(/\{(\w+)\}/g, (_, name) => values[name] == null ? '' : String(values[name]));
}

export function getLocale(language) {
  return locales[language] || locales.uk;
}
