import { baseApi } from '@shared/app/api/baseApi.js';
import { INVOICE_AFFECTING_TAGS, MANAGER_REVIEW_TAGS, WORK_TOTAL_TAGS, withSubmission, withWorkEntry } from './cacheTags.js';

export const worktrackApi = baseApi.injectEndpoints({
  endpoints: builder => ({
    getWorkSummary: builder.query({ query:(query={})=>({url:'/work-summary',params:query}), providesTags:[{type:'WorkEntries',id:'SUMMARY'}] }),
    getManagerPayroll: builder.query({ query:(query={})=>({url:'/manager/payroll',params:query}), providesTags:[{type:'WorkEntries',id:'PAYROLL'}] }),
    getManagerAdvances: builder.query({ query:(query={})=>({url:'/manager/advances',params:query}), providesTags:[{type:'WorkEntries',id:'ADVANCES'}] }),
    createManagerAdvance: builder.mutation({ query:body=>({url:'/manager/advances',method:'POST',body}), invalidatesTags:[{type:'WorkEntries',id:'ADVANCES'},{type:'WorkEntries',id:'PAYROLL'},{type:'WorkEntries',id:'SUMMARY'}] }),
    deleteManagerAdvance: builder.mutation({ query:advanceId=>({url:`/manager/advances/${advanceId}`,method:'DELETE'}), invalidatesTags:[{type:'WorkEntries',id:'ADVANCES'},{type:'WorkEntries',id:'PAYROLL'},{type:'WorkEntries',id:'SUMMARY'}] }),
    getEmployeeAdvances: builder.query({ query:(query={})=>({url:'/advances',params:query}), providesTags:[{type:'WorkEntries',id:'ADVANCES'}] }),
    getNotifications: builder.query({ query:()=>'/notifications', providesTags:[{type:'Notifications',id:'LIST'}] }),
    markNotificationRead: builder.mutation({ query:notificationId=>({url:`/notifications/${notificationId}/read`,method:'POST'}), invalidatesTags:[{type:'Notifications',id:'LIST'}] }),
    markAllNotificationsRead: builder.mutation({ query:()=>({url:'/notifications/read-all',method:'POST'}), invalidatesTags:[{type:'Notifications',id:'LIST'}] }),
    getProjects: builder.query({ query:()=>'/projects', providesTags:result=>[{type:'Projects',id:'LIST'},...(Array.isArray(result?.projects)?result.projects:[]).map(project=>({type:'Projects',id:project.id}))] }),
    getDefaultProject: builder.query({ query:()=>'/default-project', providesTags:[{type:'Projects',id:'DEFAULT'}] }),
    updateDefaultProject: builder.mutation({ query:projectId=>({url:'/default-project',method:'PATCH',body:{projectId}}), invalidatesTags:[{type:'Projects',id:'DEFAULT'}] }),
    createProject: builder.mutation({ query:body=>({url:'/projects',method:'POST',body}), invalidatesTags:[{type:'Projects',id:'LIST'},...WORK_TOTAL_TAGS] }),
    updateProject: builder.mutation({ query:({projectId,...body})=>({url:`/projects/${projectId}`,method:'PATCH',body}), invalidatesTags:(_r,_e,{projectId})=>[{type:'Projects',id:'LIST'},{type:'Projects',id:projectId},...WORK_TOTAL_TAGS] }),
    deactivateProject: builder.mutation({ query:projectId=>({url:`/projects/${projectId}/deactivate`,method:'POST'}), invalidatesTags:(_r,_e,projectId)=>[{type:'Projects',id:'LIST'},{type:'Projects',id:projectId},...WORK_TOTAL_TAGS] }),
    getCompanySettings: builder.query({ query:()=>'/company-settings', providesTags:[{type:'Company',id:'SETTINGS'}] }),
    updateCompanySettings: builder.mutation({ query:body=>({url:'/company-settings',method:'PATCH',body}), invalidatesTags:[{type:'Company',id:'SETTINGS'},{type:'Me',id:'CURRENT'},...WORK_TOTAL_TAGS] }),
    getWorkRules: builder.query({ query:()=>'/work-rules', providesTags:[{type:'Company',id:'WORK_RULES'}] }),
    updateWorkRules: builder.mutation({ query:body=>({url:'/work-rules',method:'PATCH',body}), invalidatesTags:[{type:'Company',id:'WORK_RULES'},...INVOICE_AFFECTING_TAGS,{type:'Employees',id:'LIST'},{type:'WeeklySubmissions',id:'LIST'}] }),
    getWeekEntries: builder.query({ query:(query={})=>({url:'/work-entries',params:query}), providesTags:result=>[{type:'WorkEntries',id:'WEEK'},...(Array.isArray(result?.entries)?result.entries:[]).map(entry=>({type:'WorkEntries',id:entry.id}))] }),
    createWorkEntry: builder.mutation({ query:payload=>({url:'/work-entries',method:'POST',body:payload}), invalidatesTags:INVOICE_AFFECTING_TAGS }),
    updateWorkEntry: builder.mutation({ query:({entryId,...body})=>({url:`/work-entries/${entryId}`,method:'PATCH',body}), invalidatesTags:(_r,_e,{entryId})=>withWorkEntry(entryId) }),
    deleteWorkEntry: builder.mutation({ query:entryId=>({url:`/work-entries/${entryId}`,method:'DELETE'}), invalidatesTags:(_r,_e,entryId)=>withWorkEntry(entryId) }),
    submitWeek: builder.mutation({ query:payload=>({url:'/weekly-submissions',method:'POST',body:payload}), invalidatesTags:[...INVOICE_AFFECTING_TAGS,{type:'WeeklySubmissions',id:'LIST'},{type:'Notifications',id:'LIST'}] }),
    getManagerEmployees: builder.query({ query:()=>'/manager/employees', providesTags:result=>[{type:'Employees',id:'LIST'},...(Array.isArray(result?.employees)?result.employees:[]).map(employee=>({type:'Employees',id:employee.id}))] }),
    createManagerEmployee: builder.mutation({ query:body=>({url:'/manager/employees',method:'POST',body}), invalidatesTags:[{type:'Employees',id:'LIST'},...WORK_TOTAL_TAGS] }),
    updateManagerEmployee: builder.mutation({ query:({employeeId,...body})=>({url:`/manager/employees/${employeeId}`,method:'PATCH',body}), invalidatesTags:(_r,_e,{employeeId})=>[{type:'Employees',id:'LIST'},{type:'Employees',id:employeeId},...WORK_TOTAL_TAGS,'InvoicePreview'] }),
    resetManagerEmployeePassword: builder.mutation({ query:({employeeId,temporaryPassword})=>({url:`/manager/employees/${employeeId}/reset-password`,method:'POST',body:{temporaryPassword}}) }),
    getManagerSubmissions: builder.query({ query:(query={})=>({url:'/manager/submissions',params:query}), providesTags:result=>[{type:'WeeklySubmissions',id:'LIST'},...(Array.isArray(result?.submissions)?result.submissions:[]).map(submission=>({type:'WeeklySubmissions',id:submission.id}))] }),
    getManagerSubmission: builder.query({ query:submissionId=>`/manager/submissions/${submissionId}`, providesTags:(_r,_e,submissionId)=>[{type:'WeeklySubmissions',id:submissionId}] }),
    deleteManagerWorkEntry: builder.mutation({ query:entryId=>({url:`/manager/work-entries/${entryId}`,method:'DELETE'}), invalidatesTags:MANAGER_REVIEW_TAGS }),
    clearManagerSubmission: builder.mutation({ query:submissionId=>({url:`/manager/submissions/${submissionId}/clear`,method:'DELETE'}), invalidatesTags:MANAGER_REVIEW_TAGS }),
    approveSubmission: builder.mutation({ query:submissionId=>({url:`/manager/submissions/${submissionId}/approve`,method:'POST'}), invalidatesTags:(_r,_e,submissionId)=>withSubmission(submissionId,{notifications:true}) }),
    rejectSubmission: builder.mutation({ query:({submissionId,rejectionReason})=>({url:`/manager/submissions/${submissionId}/reject`,method:'POST',body:{rejectionReason}}), invalidatesTags:(_r,_e,{submissionId})=>withSubmission(submissionId,{notifications:true}) }),
  }),
});

export const {
  useGetWorkSummaryQuery,useGetManagerPayrollQuery,useGetManagerAdvancesQuery,useCreateManagerAdvanceMutation,useDeleteManagerAdvanceMutation,useGetEmployeeAdvancesQuery,useGetNotificationsQuery,useMarkNotificationReadMutation,useMarkAllNotificationsReadMutation,
  useGetProjectsQuery,useGetDefaultProjectQuery,useUpdateDefaultProjectMutation,useCreateProjectMutation,useUpdateProjectMutation,useDeactivateProjectMutation,useGetCompanySettingsQuery,useUpdateCompanySettingsMutation,
  useGetWorkRulesQuery,useUpdateWorkRulesMutation,
  useGetWeekEntriesQuery,useCreateWorkEntryMutation,useUpdateWorkEntryMutation,useDeleteWorkEntryMutation,useSubmitWeekMutation,
  useGetManagerEmployeesQuery,useCreateManagerEmployeeMutation,useUpdateManagerEmployeeMutation,useResetManagerEmployeePasswordMutation,
  useGetManagerSubmissionsQuery,useGetManagerSubmissionQuery,useDeleteManagerWorkEntryMutation,useClearManagerSubmissionMutation,useApproveSubmissionMutation,useRejectSubmissionMutation,
} = worktrackApi;
