import { useEffect, useRef } from 'react';

const DAY_MS=86400000;
export const HOURS=Array.from({length:24},(_,i)=>String(i).padStart(2,'0')),MINUTES=['00','10','20','30','40','50'];
export const FAST_HOURS_COPY={
 uk:{project:'Об’єкт / проєкт',addShift:'Додати зміну',editShift:'Редагувати зміну',from:'Від',to:'До',note:'Нотатка',notePlaceholder:'Наприклад: монтаж, сервіс, додаткові роботи…',saveShift:'Зберегти зміну',deleteShift:'Видалити зміну',quickTitle:'Швидке заповнення тижня',quickCopy:'Заповнити робочі дні за графіком',apply:'Застосувати до вибраних днів',selectDays:'Виберіть хоча б один день',invalidTime:'Перевірте час початку та завершення',weekTotal:'Чисті години за тиждень',overtime:'Понаднормово',autoSaved:'Основний об’єкт',noShift:'Немає зміни',submit:'Відправити тиждень менеджеру',locked:'Відправлені або погоджені дні заблоковано. Решту тижня можна продовжувати редагувати.',saved:'Зміну збережено',quickSaved:'Тиждень оновлено',close:'Закрити',thisWeek:'Цей тиждень',gross:'Фактично',break:'Обід',net:'Чистими',myHours:'Мої години',weeklyNorm:'год норми',choosePrimary:'Виберіть основний об’єкт',defaultSaved:'Основний об’єкт змінено',primary:'Основний',selectTime:'Виберіть час',hours:'Години',minutes:'Хвилини',reset:'Скинути',minuteStep:'Хвилини з кроком 10: 00, 10, 20, 30, 40, 50',status:{DRAFT:'Чернетка',SUBMITTED:'Відправлено',APPROVED:'Погоджено',REJECTED:'Відхилено'}},
 cs:{project:'Objekt / projekt',addShift:'Přidat směnu',editShift:'Upravit směnu',from:'Od',to:'Do',note:'Poznámka',notePlaceholder:'Např. montáž, servis, vícepráce…',saveShift:'Uložit směnu',deleteShift:'Smazat směnu',quickTitle:'Rychlé vyplnění týdne',quickCopy:'Vyplnit pracovní dny podle rozvrhu',apply:'Použít na vybrané dny',selectDays:'Vyberte alespoň jeden den',invalidTime:'Zkontrolujte čas začátku a konce',weekTotal:'Čisté hodiny za týden',overtime:'Přesčas',autoSaved:'Hlavní objekt',noShift:'Bez směny',submit:'Odeslat týden manažerovi',locked:'Odeslané nebo schválené dny jsou uzamčeny. Zbytek týdne lze dál upravovat.',saved:'Směna uložena',quickSaved:'Týden aktualizován',close:'Zavřít',thisWeek:'Tento týden',gross:'Skutečně',break:'Oběd',net:'Čisté',myHours:'Moje hodiny',weeklyNorm:'hod normy',choosePrimary:'Vyberte hlavní objekt',defaultSaved:'Hlavní objekt byl změněn',primary:'Hlavní',selectTime:'Vyberte čas',hours:'Hodiny',minutes:'Minuty',reset:'Resetovat',minuteStep:'Minuty po 10: 00, 10, 20, 30, 40, 50',status:{DRAFT:'Koncept',SUBMITTED:'Odesláno',APPROVED:'Schváleno',REJECTED:'Zamítnuto'}},
 en:{project:'Project / site',addShift:'Add shift',editShift:'Edit shift',from:'From',to:'To',note:'Note',notePlaceholder:'For example: installation, service, extra work…',saveShift:'Save shift',deleteShift:'Delete shift',quickTitle:'Quick fill week',quickCopy:'Fill workdays from a schedule',apply:'Apply to selected days',selectDays:'Select at least one day',invalidTime:'Check the start and end time',weekTotal:'Net hours this week',overtime:'Overtime',autoSaved:'Primary site',noShift:'No shift',submit:'Send week to manager',locked:'Submitted or approved days are locked. The rest of the week can still be edited.',saved:'Shift saved',quickSaved:'Week updated',close:'Close',thisWeek:'This week',gross:'Gross',break:'Lunch',net:'Net',myHours:'My hours',weeklyNorm:'h target',choosePrimary:'Choose primary site',defaultSaved:'Primary site updated',primary:'Primary',selectTime:'Select time',hours:'Hours',minutes:'Minutes',reset:'Reset',minuteStep:'Minutes in 10-minute steps: 00, 10, 20, 30, 40, 50',status:{DRAFT:'Draft',SUBMITTED:'Submitted',APPROVED:'Approved',REJECTED:'Rejected'}}
};
const dateKey=d=>new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())).toISOString().slice(0,10);
const weekStartForDate=v=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(String(v||'')))return '';const d=new Date(`${v}T00:00:00Z`),day=d.getUTCDay();return Number.isNaN(d.getTime())?'':new Date(d.getTime()+(day===0?-6:1-day)*DAY_MS).toISOString().slice(0,10)};
export function weekStartNow(){const d=new Date(),day=d.getDay();d.setDate(d.getDate()+(day===0?-6:1-day));return dateKey(d)}
export const initialWeek=current=>weekStartForDate(new URLSearchParams(window.location.search).get('date'))||current;
export const shiftWeek=(key,amount)=>new Date(new Date(`${key}T00:00:00Z`).getTime()+amount*7*DAY_MS).toISOString().slice(0,10);
export const localeFor=l=>l==='cs'?'cs-CZ':l==='en'?'en-GB':'uk-UA';
export const fmtLong=(v,l)=>new Intl.DateTimeFormat(localeFor(l),{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${v}T00:00:00Z`));
export function fmtWeekRange(days,l){if(!days.length)return '';const o={day:'numeric',month:'long',timeZone:'UTC'},f=new Intl.DateTimeFormat(localeFor(l),o);return `${f.format(new Date(`${days[0].date}T00:00:00Z`))} — ${f.format(new Date(`${days.at(-1).date}T00:00:00Z`))}`}
export function fmtDayParts(v,l){const d=new Date(`${v}T00:00:00Z`),f=o=>new Intl.DateTimeFormat(localeFor(l),{...o,timeZone:'UTC'}).format(d).replace('.','');return{weekday:f({weekday:'short'}),date:f({day:'numeric',month:'short'})}}
const timeToMinutes=v=>{if(!/^\d{2}:\d{2}$/.test(v||''))return null;const[h,m]=v.split(':').map(Number);return h>23||m>59?null:h*60+m};
export function calculateHours(s,e){const a=timeToMinutes(s);let b=timeToMinutes(e);if(a==null||b==null)return 0;if(b<=a)b+=1440;return Math.round((b-a)/60*100)/100}
const splitHours=v=>{const m=Math.round((Number(v)||0)*60);return[Math.floor(m/60),m%60]};
export function formatHours(v){const[h,m]=splitHours(v);return `${h}h ${String(m).padStart(2,'0')}m`}
export function formatHoursShort(v,l){const[h,m]=splitHours(v);return l==='uk'?(m?`${h} год ${m} хв`:`${h} год`):l==='cs'?(m?`${h} h ${m} min`:`${h} h`):(m?`${h}h ${m}m`:`${h}h`)}
export function formatBreak(v,l){const m=Number(v||0);return l==='uk'?(m===60?'1 год':`${m} хв`):l==='cs'?(m===60?'1 h':`${m} min`):(m===60?'1h':`${m}m`)}
export const dayEntries=(entries,date)=>entries.filter(x=>x.workDate===date).sort((a,b)=>String(a.startTime||'').localeCompare(String(b.startTime||'')));
export const getDayTotal=(entries,date)=>dayEntries(entries,date).reduce((sum,x)=>sum+(Number(x.hours)||0),0);
export const closestMinute=raw=>MINUTES.reduce((best,item)=>Math.abs(Number(item)-Number(raw||0))<Math.abs(Number(best)-Number(raw||0))?item:best,'00');
const isLockedStatus=status=>status==='SUBMITTED'||status==='APPROVED';
export const entryLocked=entry=>isLockedStatus(entry?.status);
export const dateLocked=(date,submissions)=>submissions.some(s=>isLockedStatus(s.status)&&s.weekStart<=date&&s.weekEnd>=date);
export function UiIcon({type}){if(type==='building')return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 21V4.8c0-.7.5-1.3 1.2-1.5l7-2.1c.9-.3 1.8.4 1.8 1.3V21M15 8h4c.6 0 1 .4 1 1v12M3 21h19M8 7h3M8 11h3M8 15h3M8 19h3M17 12h1M17 16h1"/></svg>;if(type==='lunch')return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3v7M8 3v7M3 6h7M6.5 10v11M16 3v18M16 3c3 2 4 5 4 8h-4"/></svg>;if(type==='calendar')return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2ZM7 2v4M17 2v4M3 9h18"/></svg>;return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3.5 2"/></svg>}
export const TimeField=({value,onClick,disabled})=><button className="timeField" type="button" disabled={disabled} onClick={onClick}><span className="timeFieldIcon"><UiIcon type="clock"/></span><strong>{value}</strong><span className="timeFieldChevron">⌄</span></button>;
export const SummaryStat=({tone,icon,label,value})=><div className={`shiftSummaryStat is-${tone}`}><span className="shiftSummaryIcon"><UiIcon type={icon}/></span><span className="shiftSummaryText"><small>{label}</small><strong>{value}</strong></span></div>;
export function WheelColumn({values,value,onChange,label}){const ref=useRef(null);useEffect(()=>{ref.current?.querySelector(`[data-value="${value}"]`)?.scrollIntoView({block:'center'})},[value]);return <div className="timeWheel"><span className="timeWheelLabel">{label}</span><div className="timeWheelList" ref={ref}>{values.map(item=><button type="button" data-value={item} className={item===value?'is-active':''} onClick={()=>onChange(item)} key={item}>{item}</button>)}</div></div>}
