export const FAST_HOURS_COPY = {
  uk: {
    project: 'Об’єкт / проєкт', addShift: 'Додати зміну', editShift: 'Редагувати зміну', from: 'Від', to: 'До', note: 'Нотатка', notePlaceholder: 'Наприклад: монтаж, сервіс, додаткові роботи…', saveShift: 'Зберегти зміну', deleteShift: 'Видалити зміну', quickTitle: 'Швидке заповнення тижня', quickCopy: 'Заповнити робочі дні за графіком', apply: 'Застосувати до вибраних днів', selectDays: 'Виберіть хоча б один день', invalidTime: 'Перевірте час початку та завершення', weekTotal: 'Чисті години за тиждень', overtime: 'Понаднормово', autoSaved: 'Основний об’єкт', noShift: 'Немає зміни', submit: 'Відправити тиждень менеджеру', locked: 'Відправлені або погоджені дні заблоковано. Решту тижня можна продовжувати редагувати.', saved: 'Зміну збережено', quickSaved: 'Тиждень оновлено', close: 'Закрити', thisWeek: 'Цей тиждень', gross: 'Фактично', break: 'Обід', net: 'Чистими', myHours: 'Мої години', weeklyNorm: 'год норми', choosePrimary: 'Виберіть основний об’єкт', defaultSaved: 'Основний об’єкт змінено', primary: 'Основний', selectTime: 'Виберіть час', hours: 'Години', minutes: 'Хвилини', reset: 'Скинути', minuteStep: 'Хвилини з кроком 10: 00, 10, 20, 30, 40, 50',
    status: { DRAFT: 'Чернетка', SUBMITTED: 'Відправлено', APPROVED: 'Погоджено', REJECTED: 'Відхилено' },
  },
  cs: {
    project: 'Objekt / projekt', addShift: 'Přidat směnu', editShift: 'Upravit směnu', from: 'Od', to: 'Do', note: 'Poznámka', notePlaceholder: 'Např. montáž, servis, vícepráce…', saveShift: 'Uložit směnu', deleteShift: 'Smazat směnu', quickTitle: 'Rychlé vyplnění týdne', quickCopy: 'Vyplnit pracovní dny podle rozvrhu', apply: 'Použít na vybrané dny', selectDays: 'Vyberte alespoň jeden den', invalidTime: 'Zkontrolujte čas začátku a konce', weekTotal: 'Čisté hodiny za týden', overtime: 'Přesčas', autoSaved: 'Hlavní objekt', noShift: 'Bez směny', submit: 'Odeslat týden manažerovi', locked: 'Odeslané nebo schválené dny jsou uzamčeny. Zbytek týdne lze dál upravovat.', saved: 'Směna uložena', quickSaved: 'Týden aktualizován', close: 'Zavřít', thisWeek: 'Tento týden', gross: 'Skutečně', break: 'Oběd', net: 'Čisté', myHours: 'Moje hodiny', weeklyNorm: 'hod normy', choosePrimary: 'Vyberte hlavní objekt', defaultSaved: 'Hlavní objekt byl změněn', primary: 'Hlavní', selectTime: 'Vyberte čas', hours: 'Hodiny', minutes: 'Minuty', reset: 'Resetovat', minuteStep: 'Minuty po 10: 00, 10, 20, 30, 40, 50',
    status: { DRAFT: 'Koncept', SUBMITTED: 'Odesláno', APPROVED: 'Schváleno', REJECTED: 'Zamítnuto' },
  },
  en: {
    project: 'Project / site', addShift: 'Add shift', editShift: 'Edit shift', from: 'From', to: 'To', note: 'Note', notePlaceholder: 'For example: installation, service, extra work…', saveShift: 'Save shift', deleteShift: 'Delete shift', quickTitle: 'Quick fill week', quickCopy: 'Fill workdays from a schedule', apply: 'Apply to selected days', selectDays: 'Select at least one day', invalidTime: 'Check the start and end time', weekTotal: 'Net hours this week', overtime: 'Overtime', autoSaved: 'Primary site', noShift: 'No shift', submit: 'Send week to manager', locked: 'Submitted or approved days are locked. The rest of the week can still be edited.', saved: 'Shift saved', quickSaved: 'Week updated', close: 'Close', thisWeek: 'This week', gross: 'Gross', break: 'Lunch', net: 'Net', myHours: 'My hours', weeklyNorm: 'h target', choosePrimary: 'Choose primary site', defaultSaved: 'Primary site updated', primary: 'Primary', selectTime: 'Select time', hours: 'Hours', minutes: 'Minutes', reset: 'Reset', minuteStep: 'Minutes in 10-minute steps: 00, 10, 20, 30, 40, 50',
    status: { DRAFT: 'Draft', SUBMITTED: 'Submitted', APPROVED: 'Approved', REJECTED: 'Rejected' },
  },
};
