import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { getApiErrorMessage } from '@shared/app/api/getApiErrorMessage.js';
import { RequestLoadingState } from '@shared/app/components/RequestLoader/RequestLoader.jsx';
import { useI18n } from '@shared/app/i18n/useI18n.js';
import { formatCzk, getLocalDateKey, resolveLocale } from '../../app/formatters.js';
import { useDeleteManagerAdvanceMutation, useGetManagerAdvancesQuery } from '../../features/worktrack/worktrackApi.js';
import './ManagerAdvancesPage.css';

const COPY={
  uk:{title:'Аванси',subtitle:'Аванси віднімаються від чистої зарплати працівника.',month:'Місяць',add:'Додати аванс',employee:'Працівник',allEmployees:'Усі працівники',amount:'Сума',received:'Видано за місяць',count:'Кількість авансів',active:'Активних авансів',payments:'виплат',history:'Історія авансів',empty:'За цей місяць авансів немає',delete:'Видалити',confirmDelete:'Видалити цей аванс?',status:'Статус',activeStatus:'Активний',balance:'Залишок',impact:'Впливає на чисту зарплату',impactText:'Ця сума буде віднята від майбутніх виплат працівнику.'},
 cs:{title:'Zálohy',subtitle:'Zálohy se odečítají od čisté mzdy zaměstnance.',month:'Měsíc',add:'Přidat zálohu',employee:'Zaměstnanec',allEmployees:'Všichni zaměstnanci',amount:'Částka',received:'Vyplaceno za měsíc',count:'Počet záloh',active:'Aktivní zálohy',payments:'plateb',history:'Historie záloh',empty:'V tomto měsíci nejsou žádné zálohy',delete:'Smazat',confirmDelete:'Smazat tuto zálohu?',status:'Stav',activeStatus:'Aktivní',balance:'Zůstatek',impact:'Ovlivňuje čistou mzdu',impactText:'Tato částka bude odečtena od budoucích výplat zaměstnance.'},
 en:{title:'Advances',subtitle:'Advances are deducted from the employee’s net salary.',month:'Month',add:'Add advance',employee:'Employee',allEmployees:'All employees',amount:'Amount',received:'Paid this month',count:'Number of advances',active:'Active advances',payments:'payments',history:'Advance history',empty:'No advances for this month',delete:'Delete',confirmDelete:'Delete this advance?',status:'Status',activeStatus:'Active',balance:'Balance',impact:'Affects net salary',impactText:'This amount will be deducted from the employee’s future payments.'}
};
function monthKey(dateKey){return String(dateKey||getLocalDateKey()).slice(0,7)}
function AdvanceIcon({type}){if(type==='calendar')return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3v3M17 3v3M4.5 9h15M6 5h12a2 2 0 0 1 2 2v12H4V7a2 2 0 0 1 2-2Z"/></svg>;if(type==='wallet')return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 6.5h12.5A2.5 2.5 0 0 1 20 9v9H5a2 2 0 0 1-2-2V6.5h2Zm0 0V5a2 2 0 0 1 2-2h9M15 11h5v4h-5a2 2 0 1 1 0-4Z"/></svg>;return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 4v13m0 0-4-4m4 4 4-4M5 20h14"/></svg>}
export function ManagerAdvancesPage({embedded=false}){
 const navigate=useNavigate(); const {language}=useI18n(); const copy=COPY[language]||COPY.uk; const locale=resolveLocale(language);
 const [month,setMonth]=useState(monthKey(getLocalDateKey())); const [filterEmployee,setFilterEmployee]=useState('');
 const query=useGetManagerAdvancesQuery({month}); const [deleteAdvance,deleteState]=useDeleteManagerAdvanceMutation();
 const employees=query.data?.employees||[]; const advances=query.data?.advances||[]; const total=Number(query.data?.summary?.totalCzk||0); const error=query.error||deleteState.error;
 const visible=useMemo(()=>filterEmployee?advances.filter(item=>String(item.employee?.id||item.employeeMembershipId||'')===filterEmployee):advances,[advances,filterEmployee]);
 const grouped=useMemo(()=>{const map=new Map();visible.forEach(item=>{const key=item.paidAt;if(!map.has(key))map.set(key,[]);map.get(key).push(item)});return [...map.entries()]},[visible]);
 async function handleDelete(id){if(!window.confirm(copy.confirmDelete))return;await deleteAdvance(id).unwrap()}
 if(embedded)return null;
 return <section className="managerAdvancesPage pageStack">
  <header className="managerAdvances-header"><div><h1>{copy.title}</h1><p>{copy.subtitle}</p></div><button type="button" className="managerAdvances-addButton" onClick={()=>navigate('/manager/advances/new')} aria-label={copy.add}><b>＋</b><span>{copy.add}</span></button></header>
  <section className="managerAdvances-stats"><div><i><AdvanceIcon type="down"/></i><span>{copy.received}</span><strong>{formatCzk(total,locale)}</strong><small>{advances.length} {copy.payments}</small></div><div><i><AdvanceIcon type="calendar"/></i><span>{copy.count}</span><strong>{advances.length}</strong><small>{new Intl.DateTimeFormat(locale,{month:'long',timeZone:'UTC'}).format(new Date(`${month}-01T00:00:00Z`))}</small></div><div><i><AdvanceIcon type="wallet"/></i><span>{copy.active}</span><strong>{advances.length}</strong></div></section>
  <section className="managerAdvances-filters"><label><span>{copy.month}</span><input type="month" value={month} onChange={e=>setMonth(e.target.value||monthKey(getLocalDateKey()))}/></label><label><span>{copy.employee}</span><select value={filterEmployee} onChange={e=>setFilterEmployee(e.target.value)}><option value="">{copy.allEmployees}</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></section>
  {error?<p className="statusNote is-error">{getApiErrorMessage(error)}</p>:null}{query.isLoading?<RequestLoadingState label={copy.history}/>:null}
  {!query.isLoading?<section className="managerAdvances-history"><div className="managerAdvances-sectionTitle"><h2>{copy.history}</h2><span>{visible.length}</span></div>{grouped.length?grouped.map(([date,items])=><div className="managerAdvances-day" key={date}>{items.map(item=><article className="managerAdvances-record" key={item.id}><div className="managerAdvances-recordTop"><span className="managerAdvances-date"><AdvanceIcon type="calendar"/>{new Intl.DateTimeFormat(locale,{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${date}T00:00:00Z`))}</span><strong>− {formatCzk(item.amountCzk,locale)}</strong></div><div className="managerAdvances-person"><div className="managerAdvances-avatar">{(item.employee?.name||'?').trim().charAt(0).toUpperCase()}</div><div><strong>{item.employee?.name||'—'}</strong><span>{item.note||item.employee?.email||''}</span></div><button type="button" disabled={deleteState.isLoading} onClick={()=>handleDelete(item.id)}>•••<small>{copy.delete}</small></button></div><div className="managerAdvances-details"><div><span>{copy.amount}</span><strong>{formatCzk(item.amountCzk,locale)}</strong></div><div><span>{copy.status}</span><b>{copy.activeStatus}</b></div><div><span>{copy.balance}</span><strong>{formatCzk(item.amountCzk,locale)}</strong></div></div><div className="managerAdvances-impact"><i>i</i><div><strong>{copy.impact}</strong><span>{copy.impactText}</span></div></div></article>)}</div>):<div className="managerAdvances-empty">{copy.empty}</div>}</section>:null}
 </section>
}
