import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getApiErrorMessage } from '@shared/app/api/getApiErrorMessage.js';
import { useI18n } from '@shared/app/i18n/useI18n.js';
import { getLocalDateKey } from '../../app/formatters.js';
import { useCreateManagerExpenseMutation } from '../../features/worktrack/worktrackApi.js';
import './ManagerExpenseCreatePage.css';
const COPY={uk:{title:'Нова витрата',subtitle:'Додайте витрату компанії',category:'Категорія',amount:'Сума',date:'Дата',note:'Примітка',optional:'необов’язково',save:'Зберегти витрату',saving:'Збереження…',notePlaceholder:'Наприклад: купівля матеріалів'},cs:{title:'Nový výdaj',subtitle:'Přidejte firemní výdaj',category:'Kategorie',amount:'Částka',date:'Datum',note:'Poznámka',optional:'nepovinné',save:'Uložit výdaj',saving:'Ukládání…',notePlaceholder:'Např. nákup materiálu'},en:{title:'New expense',subtitle:'Add a company expense',category:'Category',amount:'Amount',date:'Date',note:'Note',optional:'optional',save:'Save expense',saving:'Saving…',notePlaceholder:'For example: materials purchase'}};
const CATS={MATERIALS:{uk:'Матеріали',cs:'Materiál',en:'Materials'},TRANSPORT:{uk:'Транспорт',cs:'Doprava',en:'Transport'},FUEL:{uk:'Паливо',cs:'Palivo',en:'Fuel'},TOOLS:{uk:'Інструменти',cs:'Nářadí',en:'Tools'},OFFICE:{uk:'Офіс',cs:'Kancelář',en:'Office'},OTHER:{uk:'Інше',cs:'Ostatní',en:'Other'}};
export function ManagerExpenseCreatePage(){const navigate=useNavigate();const {language}=useI18n();const c=COPY[language]||COPY.uk;const [category,setCategory]=useState('MATERIALS');const [amountCzk,setAmountCzk]=useState('');const [spentAt,setSpentAt]=useState(getLocalDateKey());const [note,setNote]=useState('');const [createExpense,state]=useCreateManagerExpenseMutation();const canSubmit=Number(String(amountCzk).replace(',','.'))>0&&spentAt&&!state.isLoading;async function submit(e){e.preventDefault();if(!canSubmit)return;await createExpense({category,amountCzk:String(amountCzk).replace(',','.'),spentAt,note}).unwrap();navigate('/manager/expenses',{replace:true})}return <section className="expenseCreatePage pageStack"><header className="expenseCreate-header"><button type="button" onClick={()=>navigate(-1)}>‹</button><div><h1>{c.title}</h1><p>{c.subtitle}</p></div></header><form className="expenseCreate-card" onSubmit={submit}><label><span>{c.category}</span><select value={category} onChange={e=>setCategory(e.target.value)}>{Object.keys(CATS).map(key=><option key={key} value={key}>{CATS[key][language]||CATS[key].uk}</option>)}</select></label><label><span>{c.amount}</span><div className="expenseCreate-money"><input inputMode="decimal" value={amountCzk} onChange={e=>setAmountCzk(e.target.value)} placeholder="0" required/><b>Kč</b></div></label><label><span>{c.date}</span><input type="date" value={spentAt} onChange={e=>setSpentAt(e.target.value)} required/></label><label><span>{c.note} <em>({c.optional})</em></span><input value={note} maxLength={500} onChange={e=>setNote(e.target.value)} placeholder={c.notePlaceholder}/></label>{state.error?<p className="statusNote is-error">{getApiErrorMessage(state.error)}</p>:null}<button className="expenseCreate-save" type="submit" disabled={!canSubmit}>{state.isLoading?c.saving:c.save}</button></form></section>}
